
# This file is automatically generated, you probably don't want to edit this

a2tablesgraphsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a2tablesgraphsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            ecdf = NULL,
            absH = FALSE,
            cumH = FALSE,
            stick = FALSE,
            stickrel = FALSE,
            vbar = FALSE,
            vbarrel = FALSE,
            hbar = FALSE,
            hbarrel = FALSE,
            pie = FALSE,
            line = FALSE,
            linerel = FALSE,
            empV = FALSE, ...) {

            super$initialize(
                package="jamoviRWTH",
                name="a2tablesgraphs",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                permitted=list(
                    "factor",
                    "id",
                    "numeric"),
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..ecdf <- jmvcore::OptionVariables$new(
                "ecdf",
                ecdf,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "ordinal",
                    "continuous"))
            private$..absH <- jmvcore::OptionBool$new(
                "absH",
                absH,
                default=FALSE)
            private$..cumH <- jmvcore::OptionBool$new(
                "cumH",
                cumH,
                default=FALSE)
            private$..stick <- jmvcore::OptionBool$new(
                "stick",
                stick,
                default=FALSE)
            private$..stickrel <- jmvcore::OptionBool$new(
                "stickrel",
                stickrel,
                default=FALSE)
            private$..vbar <- jmvcore::OptionBool$new(
                "vbar",
                vbar,
                default=FALSE)
            private$..vbarrel <- jmvcore::OptionBool$new(
                "vbarrel",
                vbarrel,
                default=FALSE)
            private$..hbar <- jmvcore::OptionBool$new(
                "hbar",
                hbar,
                default=FALSE)
            private$..hbarrel <- jmvcore::OptionBool$new(
                "hbarrel",
                hbarrel,
                default=FALSE)
            private$..pie <- jmvcore::OptionBool$new(
                "pie",
                pie,
                default=FALSE)
            private$..line <- jmvcore::OptionBool$new(
                "line",
                line,
                default=FALSE)
            private$..linerel <- jmvcore::OptionBool$new(
                "linerel",
                linerel,
                default=FALSE)
            private$..empV <- jmvcore::OptionBool$new(
                "empV",
                empV,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..ecdf)
            self$.addOption(private$..absH)
            self$.addOption(private$..cumH)
            self$.addOption(private$..stick)
            self$.addOption(private$..stickrel)
            self$.addOption(private$..vbar)
            self$.addOption(private$..vbarrel)
            self$.addOption(private$..hbar)
            self$.addOption(private$..hbarrel)
            self$.addOption(private$..pie)
            self$.addOption(private$..line)
            self$.addOption(private$..linerel)
            self$.addOption(private$..empV)
        }),
    active = list(
        vars = function() private$..vars$value,
        ecdf = function() private$..ecdf$value,
        absH = function() private$..absH$value,
        cumH = function() private$..cumH$value,
        stick = function() private$..stick$value,
        stickrel = function() private$..stickrel$value,
        vbar = function() private$..vbar$value,
        vbarrel = function() private$..vbarrel$value,
        hbar = function() private$..hbar$value,
        hbarrel = function() private$..hbarrel$value,
        pie = function() private$..pie$value,
        line = function() private$..line$value,
        linerel = function() private$..linerel$value,
        empV = function() private$..empV$value),
    private = list(
        ..vars = NA,
        ..ecdf = NA,
        ..absH = NA,
        ..cumH = NA,
        ..stick = NA,
        ..stickrel = NA,
        ..vbar = NA,
        ..vbarrel = NA,
        ..hbar = NA,
        ..hbarrel = NA,
        ..pie = NA,
        ..line = NA,
        ..linerel = NA,
        ..empV = NA)
)

a2tablesgraphsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a2tablesgraphsResults",
    inherit = jmvcore::Group,
    active = list(
        frequencies = function() private$.items[["frequencies"]],
        stickcharts = function() private$.items[["stickcharts"]],
        vbarcharts = function() private$.items[["vbarcharts"]],
        hbarcharts = function() private$.items[["hbarcharts"]],
        piecharts = function() private$.items[["piecharts"]],
        linecharts = function() private$.items[["linecharts"]],
        ecdfs = function() private$.items[["ecdfs"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Tables and Graphs (A2)")
            self$add(jmvcore::Array$new(
                options=options,
                name="frequencies",
                title="Frequencies",
                visible="(absH)",
                items="(c(vars))",
                template=jmvcore::Table$new(
                    options=options,
                    title="Frequency table of $key",
                    visible="(absH)",
                    columns=list())))
            self$add(jmvcore::Array$new(
                options=options,
                name="stickcharts",
                title="Stick charts",
                visible="(stick)",
                items="(c(vars))",
                template=jmvcore::Image$new(
                    options=options,
                    title="Stick chart for $key",
                    visible="(stick)",
                    renderFun=".chart")))
            self$add(jmvcore::Array$new(
                options=options,
                name="vbarcharts",
                title="Vertical bar charts",
                visible="(vbar)",
                items="(c(vars))",
                template=jmvcore::Image$new(
                    options=options,
                    title="Vertical bar chart for $key",
                    visible="(vbar)",
                    renderFun=".chart")))
            self$add(jmvcore::Array$new(
                options=options,
                name="hbarcharts",
                title="Horizontal bar charts",
                visible="(hbar)",
                items="(c(vars))",
                template=jmvcore::Image$new(
                    options=options,
                    title="Horizontal bar chart for $key",
                    visible="(hbar)",
                    renderFun=".chart")))
            self$add(jmvcore::Array$new(
                options=options,
                name="piecharts",
                title="Pie charts",
                visible="(pie)",
                items="(c(vars))",
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        piechartplot = function() private$.items[["piechartplot"]],
                        piechartangle = function() private$.items[["piechartangle"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="")
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="piechartplot",
                                title="Pie chart for $key",
                                visible="(pie)",
                                renderFun=".piechartplot"))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="piechartangle",
                                title="Table for $key",
                                visible="(pie)",
                                columns=list()))}))$new(options=options)))
            self$add(jmvcore::Array$new(
                options=options,
                name="linecharts",
                title="Line charts",
                visible="(line)",
                items="(c(vars))",
                template=jmvcore::Image$new(
                    options=options,
                    title="Line chart for $key",
                    visible="(line)",
                    renderFun=".chart")))
            self$add(jmvcore::Array$new(
                options=options,
                name="ecdfs",
                title="Empirical distribution functions",
                visible="(empV)",
                items="(c(ecdf))",
                template=jmvcore::Image$new(
                    options=options,
                    title="Empirical distribution function for $key",
                    visible="(empV)",
                    renderFun=".ecdf")))}))

a2tablesgraphsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a2tablesgraphsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "a2tablesgraphs",
                version = c(1,0,0),
                options = options,
                results = a2tablesgraphsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Tables and Graphs (A2)
#'
#' 
#' @param data .
#' @param vars .
#' @param ecdf .
#' @param absH .
#' @param cumH .
#' @param stick .
#' @param stickrel .
#' @param vbar .
#' @param vbarrel .
#' @param hbar .
#' @param hbarrel .
#' @param pie .
#' @param line .
#' @param linerel .
#' @param empV .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$frequencies} \tab \tab \tab \tab \tab an array of frequency tables \cr
#'   \code{results$stickcharts} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$vbarcharts} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$hbarcharts} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$piecharts} \tab \tab \tab \tab \tab an array of groups \cr
#'   \code{results$linecharts} \tab \tab \tab \tab \tab an array of images \cr
#'   \code{results$ecdfs} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' @export
a2tablesgraphs <- function(
    data,
    vars,
    ecdf,
    absH = FALSE,
    cumH = FALSE,
    stick = FALSE,
    stickrel = FALSE,
    vbar = FALSE,
    vbarrel = FALSE,
    hbar = FALSE,
    hbarrel = FALSE,
    pie = FALSE,
    line = FALSE,
    linerel = FALSE,
    empV = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("a2tablesgraphs requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(ecdf)) ecdf <- jmvcore::resolveQuo(jmvcore::enquo(ecdf))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(ecdf), ecdf, NULL))


    options <- a2tablesgraphsOptions$new(
        vars = vars,
        ecdf = ecdf,
        absH = absH,
        cumH = cumH,
        stick = stick,
        stickrel = stickrel,
        vbar = vbar,
        vbarrel = vbarrel,
        hbar = hbar,
        hbarrel = hbarrel,
        pie = pie,
        line = line,
        linerel = linerel,
        empV = empV)

    analysis <- a2tablesgraphsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

