
# This file is automatically generated, you probably don't want to edit this

a3descriptivemeasuresOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a3descriptivemeasuresOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varrank = NULL,
            vars = NULL,
            group = NULL,
            Gew = NULL,
            min = FALSE,
            uQuart = FALSE,
            mod = FALSE,
            med = FALSE,
            mean = FALSE,
            wmean = FALSE,
            geomean = FALSE,
            wgeomean = FALSE,
            harmmean = FALSE,
            wharmmean = FALSE,
            oQuart = FALSE,
            max = FALSE,
            quant = FALSE,
            pquant = "5,10,15",
            varianz = FALSE,
            stAbw = FALSE,
            varkoeff = FALSE,
            QAbst = FALSE,
            range = FALSE,
            absAbw = FALSE,
            box = FALSE,
            variante = "base",
            Richtung = "horizontal", ...) {

            super$initialize(
                package="jamoviRWTH",
                name="a3descriptivemeasures",
                requiresData=TRUE,
                ...)

            private$..varrank <- jmvcore::OptionVariable$new(
                "varrank",
                varrank,
                permitted=list(
                    "factor",
                    "numeric"),
                suggested=list(
                    "ordinal",
                    "continuous"))
            private$..rank <- jmvcore::OptionOutput$new(
                "rank")
            private$..order <- jmvcore::OptionOutput$new(
                "order")
            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                permitted=list(
                    "factor",
                    "numeric"),
                suggested=list(
                    "ordinal",
                    "continuous"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                permitted=list(
                    "factor"),
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..Gew <- jmvcore::OptionVariable$new(
                "Gew",
                Gew,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..min <- jmvcore::OptionBool$new(
                "min",
                min,
                default=FALSE)
            private$..uQuart <- jmvcore::OptionBool$new(
                "uQuart",
                uQuart,
                default=FALSE)
            private$..mod <- jmvcore::OptionBool$new(
                "mod",
                mod,
                default=FALSE)
            private$..med <- jmvcore::OptionBool$new(
                "med",
                med,
                default=FALSE)
            private$..mean <- jmvcore::OptionBool$new(
                "mean",
                mean,
                default=FALSE)
            private$..wmean <- jmvcore::OptionBool$new(
                "wmean",
                wmean,
                default=FALSE)
            private$..geomean <- jmvcore::OptionBool$new(
                "geomean",
                geomean,
                default=FALSE)
            private$..wgeomean <- jmvcore::OptionBool$new(
                "wgeomean",
                wgeomean,
                default=FALSE)
            private$..harmmean <- jmvcore::OptionBool$new(
                "harmmean",
                harmmean,
                default=FALSE)
            private$..wharmmean <- jmvcore::OptionBool$new(
                "wharmmean",
                wharmmean,
                default=FALSE)
            private$..oQuart <- jmvcore::OptionBool$new(
                "oQuart",
                oQuart,
                default=FALSE)
            private$..max <- jmvcore::OptionBool$new(
                "max",
                max,
                default=FALSE)
            private$..quant <- jmvcore::OptionBool$new(
                "quant",
                quant,
                default=FALSE)
            private$..pquant <- jmvcore::OptionString$new(
                "pquant",
                pquant,
                default="5,10,15")
            private$..varianz <- jmvcore::OptionBool$new(
                "varianz",
                varianz,
                default=FALSE)
            private$..stAbw <- jmvcore::OptionBool$new(
                "stAbw",
                stAbw,
                default=FALSE)
            private$..varkoeff <- jmvcore::OptionBool$new(
                "varkoeff",
                varkoeff,
                default=FALSE)
            private$..QAbst <- jmvcore::OptionBool$new(
                "QAbst",
                QAbst,
                default=FALSE)
            private$..range <- jmvcore::OptionBool$new(
                "range",
                range,
                default=FALSE)
            private$..absAbw <- jmvcore::OptionBool$new(
                "absAbw",
                absAbw,
                default=FALSE)
            private$..box <- jmvcore::OptionBool$new(
                "box",
                box,
                default=FALSE)
            private$..variante <- jmvcore::OptionList$new(
                "variante",
                variante,
                options=list(
                    "base",
                    "modified"),
                default="base")
            private$..Richtung <- jmvcore::OptionList$new(
                "Richtung",
                Richtung,
                options=list(
                    "horizontal",
                    "vertical"),
                default="horizontal")

            self$.addOption(private$..varrank)
            self$.addOption(private$..rank)
            self$.addOption(private$..order)
            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..Gew)
            self$.addOption(private$..min)
            self$.addOption(private$..uQuart)
            self$.addOption(private$..mod)
            self$.addOption(private$..med)
            self$.addOption(private$..mean)
            self$.addOption(private$..wmean)
            self$.addOption(private$..geomean)
            self$.addOption(private$..wgeomean)
            self$.addOption(private$..harmmean)
            self$.addOption(private$..wharmmean)
            self$.addOption(private$..oQuart)
            self$.addOption(private$..max)
            self$.addOption(private$..quant)
            self$.addOption(private$..pquant)
            self$.addOption(private$..varianz)
            self$.addOption(private$..stAbw)
            self$.addOption(private$..varkoeff)
            self$.addOption(private$..QAbst)
            self$.addOption(private$..range)
            self$.addOption(private$..absAbw)
            self$.addOption(private$..box)
            self$.addOption(private$..variante)
            self$.addOption(private$..Richtung)
        }),
    active = list(
        varrank = function() private$..varrank$value,
        rank = function() private$..rank$value,
        order = function() private$..order$value,
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        Gew = function() private$..Gew$value,
        min = function() private$..min$value,
        uQuart = function() private$..uQuart$value,
        mod = function() private$..mod$value,
        med = function() private$..med$value,
        mean = function() private$..mean$value,
        wmean = function() private$..wmean$value,
        geomean = function() private$..geomean$value,
        wgeomean = function() private$..wgeomean$value,
        harmmean = function() private$..harmmean$value,
        wharmmean = function() private$..wharmmean$value,
        oQuart = function() private$..oQuart$value,
        max = function() private$..max$value,
        quant = function() private$..quant$value,
        pquant = function() private$..pquant$value,
        varianz = function() private$..varianz$value,
        stAbw = function() private$..stAbw$value,
        varkoeff = function() private$..varkoeff$value,
        QAbst = function() private$..QAbst$value,
        range = function() private$..range$value,
        absAbw = function() private$..absAbw$value,
        box = function() private$..box$value,
        variante = function() private$..variante$value,
        Richtung = function() private$..Richtung$value),
    private = list(
        ..varrank = NA,
        ..rank = NA,
        ..order = NA,
        ..vars = NA,
        ..group = NA,
        ..Gew = NA,
        ..min = NA,
        ..uQuart = NA,
        ..mod = NA,
        ..med = NA,
        ..mean = NA,
        ..wmean = NA,
        ..geomean = NA,
        ..wgeomean = NA,
        ..harmmean = NA,
        ..wharmmean = NA,
        ..oQuart = NA,
        ..max = NA,
        ..quant = NA,
        ..pquant = NA,
        ..varianz = NA,
        ..stAbw = NA,
        ..varkoeff = NA,
        ..QAbst = NA,
        ..range = NA,
        ..absAbw = NA,
        ..box = NA,
        ..variante = NA,
        ..Richtung = NA)
)

a3descriptivemeasuresResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a3descriptivemeasuresResults",
    inherit = jmvcore::Group,
    active = list(
        order = function() private$.items[["order"]],
        rank = function() private$.items[["rank"]],
        Central = function() private$.items[["Central"]],
        Disp = function() private$.items[["Disp"]],
        boxplot = function() private$.items[["boxplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Measures of Central Tendency and Dispersion (A3)")
            self$add(jmvcore::Output$new(
                options=options,
                name="order",
                title="order statistics",
                varTitle="order statistics",
                varDescription="order statistics of Variable",
                measureType="continuous"))
            self$add(jmvcore::Output$new(
                options=options,
                name="rank",
                title="Rank",
                varTitle="Rank",
                varDescription="Ranks of Variable",
                measureType="continuous"))
            self$add(jmvcore::Table$new(
                options=options,
                name="Central",
                title="Measures of Central Tendency",
                visible="(min || uQuart || mod || med|| mean || geomean || harmmean || oQuart || max | quant)",
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="Disp",
                title="Measures of Dispersion",
                visible="(range || QAbst || varianz || stAbw || absAbw || varkoeff)",
                columns=list()))
            self$add(jmvcore::Image$new(
                options=options,
                name="boxplot",
                title="Boxplot",
                visible="(box & !is.null(vars))",
                renderFun=".plot"))}))

a3descriptivemeasuresBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a3descriptivemeasuresBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "a3descriptivemeasures",
                version = c(1,0,0),
                options = options,
                results = a3descriptivemeasuresResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Measures of Central Tendency and Dispersion (A3)
#'
#' 
#' @param data .
#' @param varrank .
#' @param vars .
#' @param group .
#' @param Gew .
#' @param min .
#' @param uQuart .
#' @param mod .
#' @param med .
#' @param mean .
#' @param wmean .
#' @param geomean .
#' @param wgeomean .
#' @param harmmean .
#' @param wharmmean .
#' @param oQuart .
#' @param max .
#' @param quant .
#' @param pquant .
#' @param varianz .
#' @param stAbw .
#' @param varkoeff .
#' @param QAbst .
#' @param range .
#' @param absAbw .
#' @param box .
#' @param variante .
#' @param Richtung .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$order} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$rank} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$Central} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$Disp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$boxplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$Central$asDF}
#'
#' \code{as.data.frame(results$Central)}
#'
#' @export
a3descriptivemeasures <- function(
    data,
    varrank,
    vars,
    group,
    Gew,
    min = FALSE,
    uQuart = FALSE,
    mod = FALSE,
    med = FALSE,
    mean = FALSE,
    wmean = FALSE,
    geomean = FALSE,
    wgeomean = FALSE,
    harmmean = FALSE,
    wharmmean = FALSE,
    oQuart = FALSE,
    max = FALSE,
    quant = FALSE,
    pquant = "5,10,15",
    varianz = FALSE,
    stAbw = FALSE,
    varkoeff = FALSE,
    QAbst = FALSE,
    range = FALSE,
    absAbw = FALSE,
    box = FALSE,
    variante = "base",
    Richtung = "horizontal") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("a3descriptivemeasures requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varrank)) varrank <- jmvcore::resolveQuo(jmvcore::enquo(varrank))
    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(Gew)) Gew <- jmvcore::resolveQuo(jmvcore::enquo(Gew))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varrank), varrank, NULL),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(Gew), Gew, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- a3descriptivemeasuresOptions$new(
        varrank = varrank,
        vars = vars,
        group = group,
        Gew = Gew,
        min = min,
        uQuart = uQuart,
        mod = mod,
        med = med,
        mean = mean,
        wmean = wmean,
        geomean = geomean,
        wgeomean = wgeomean,
        harmmean = harmmean,
        wharmmean = wharmmean,
        oQuart = oQuart,
        max = max,
        quant = quant,
        pquant = pquant,
        varianz = varianz,
        stAbw = stAbw,
        varkoeff = varkoeff,
        QAbst = QAbst,
        range = range,
        absAbw = absAbw,
        box = box,
        variante = variante,
        Richtung = Richtung)

    analysis <- a3descriptivemeasuresClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

