
# This file is automatically generated, you probably don't want to edit this

a4histrogramsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a4histrogramsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            categvar = NULL,
            previewplot = FALSE,
            previewtable = FALSE,
            equitable = FALSE,
            checkboxequi = FALSE,
            equibins = 10,
            checkboxcateg = FALSE,
            breakValues = "1,2,3",
            propfactorcateg = FALSE,
            ccateg = 1,
            propfactorequi = FALSE,
            cequi = 1,
            categtable = FALSE, ...) {

            super$initialize(
                package="jamoviRWTH",
                name="a4histrograms",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..categvar <- jmvcore::OptionVariable$new(
                "categvar",
                categvar,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..previewplot <- jmvcore::OptionBool$new(
                "previewplot",
                previewplot,
                default=FALSE)
            private$..previewtable <- jmvcore::OptionBool$new(
                "previewtable",
                previewtable,
                default=FALSE)
            private$..equitable <- jmvcore::OptionBool$new(
                "equitable",
                equitable,
                default=FALSE)
            private$..checkboxequi <- jmvcore::OptionBool$new(
                "checkboxequi",
                checkboxequi,
                default=FALSE)
            private$..equibins <- jmvcore::OptionNumber$new(
                "equibins",
                equibins,
                default=10)
            private$..checkboxcateg <- jmvcore::OptionBool$new(
                "checkboxcateg",
                checkboxcateg,
                default=FALSE)
            private$..breakValues <- jmvcore::OptionString$new(
                "breakValues",
                breakValues,
                default="1,2,3")
            private$..propfactorcateg <- jmvcore::OptionBool$new(
                "propfactorcateg",
                propfactorcateg,
                default=FALSE)
            private$..ccateg <- jmvcore::OptionNumber$new(
                "ccateg",
                ccateg,
                min=0,
                default=1)
            private$..propfactorequi <- jmvcore::OptionBool$new(
                "propfactorequi",
                propfactorequi,
                default=FALSE)
            private$..cequi <- jmvcore::OptionNumber$new(
                "cequi",
                cequi,
                min=0,
                default=1)
            private$..categtable <- jmvcore::OptionBool$new(
                "categtable",
                categtable,
                default=FALSE)

            self$.addOption(private$..deps)
            self$.addOption(private$..categvar)
            self$.addOption(private$..previewplot)
            self$.addOption(private$..previewtable)
            self$.addOption(private$..equitable)
            self$.addOption(private$..checkboxequi)
            self$.addOption(private$..equibins)
            self$.addOption(private$..checkboxcateg)
            self$.addOption(private$..breakValues)
            self$.addOption(private$..propfactorcateg)
            self$.addOption(private$..ccateg)
            self$.addOption(private$..propfactorequi)
            self$.addOption(private$..cequi)
            self$.addOption(private$..categtable)
        }),
    active = list(
        deps = function() private$..deps$value,
        categvar = function() private$..categvar$value,
        previewplot = function() private$..previewplot$value,
        previewtable = function() private$..previewtable$value,
        equitable = function() private$..equitable$value,
        checkboxequi = function() private$..checkboxequi$value,
        equibins = function() private$..equibins$value,
        checkboxcateg = function() private$..checkboxcateg$value,
        breakValues = function() private$..breakValues$value,
        propfactorcateg = function() private$..propfactorcateg$value,
        ccateg = function() private$..ccateg$value,
        propfactorequi = function() private$..propfactorequi$value,
        cequi = function() private$..cequi$value,
        categtable = function() private$..categtable$value),
    private = list(
        ..deps = NA,
        ..categvar = NA,
        ..previewplot = NA,
        ..previewtable = NA,
        ..equitable = NA,
        ..checkboxequi = NA,
        ..equibins = NA,
        ..checkboxcateg = NA,
        ..breakValues = NA,
        ..propfactorcateg = NA,
        ..ccateg = NA,
        ..propfactorequi = NA,
        ..cequi = NA,
        ..categtable = NA)
)

a4histrogramsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a4histrogramsResults",
    inherit = jmvcore::Group,
    active = list(
        hists = function() private$.items[["hists"]],
        categhist = function() private$.items[["categhist"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Grouped Data and Histograms (A4)")
            self$add(jmvcore::Array$new(
                options=options,
                name="hists",
                title="Data and Histograms with equidistant bins",
                items="(c(deps))",
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        previewplot = function() private$.items[["previewplot"]],
                        summarytable = function() private$.items[["summarytable"]],
                        previewtable = function() private$.items[["previewtable"]],
                        equiplot = function() private$.items[["equiplot"]],
                        equitable = function() private$.items[["equitable"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="Data and Histograms for $key")
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="previewplot",
                                title="Preview",
                                visible="(previewplot)",
                                renderFun=".hist"))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="summarytable",
                                title="Summary statistics",
                                visible="(previewplot)",
                                rows=0,
                                columns=list(
                                    list(
                                        `name`="minimum", 
                                        `title`="Minimum", 
                                        `type`="number"),
                                    list(
                                        `name`="maximum", 
                                        `title`="Maximum", 
                                        `type`="number"),
                                    list(
                                        `name`="datalength", 
                                        `title`="Sample size", 
                                        `type`="number"),
                                    list(
                                        `name`="noofbins", 
                                        `title`="Max. number of bins recommended", 
                                        `type`="number"),
                                    list(
                                        `name`="aequi", 
                                        `title`="Width of equidistant bins in preview", 
                                        `type`="number"))))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="previewtable",
                                title="Table for equidistantly grouped data",
                                visible="(previewplot & previewtable)",
                                columns=list()))
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="equiplot",
                                title="Equidistant",
                                visible="(checkboxequi)",
                                renderFun=".hist"))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="equitable",
                                title="Table for equidistantly grouped data",
                                visible="(checkboxequi & equitable)",
                                columns=list()))}))$new(options=options)))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    categplot = function() private$.items[["categplot"]],
                    categtable = function() private$.items[["categtable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="categhist",
                            title="Data and Histograms with custom categories")
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="categplot",
                            title="Categories",
                            visible="(checkboxcateg)",
                            renderFun=".hist"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="categtable",
                            title="Table for grouped data",
                            visible="(checkboxcateg & categtable)",
                            columns=list()))}))$new(options=options))}))

a4histrogramsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a4histrogramsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "a4histrograms",
                version = c(1,0,0),
                options = options,
                results = a4histrogramsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Grouped Data and Histograms (A4)
#'
#' 
#' @param data the data as a data frame
#' @param deps the dependent variables (not necessary when using a formula,
#'   see the examples)
#' @param categvar .
#' @param previewplot .
#' @param previewtable .
#' @param equitable .
#' @param checkboxequi .
#' @param equibins .
#' @param checkboxcateg .
#' @param breakValues a comma-sepated list (default: 1,2,3) specifying the
#'   breaks of the categories and the histogram.
#' @param propfactorcateg .
#' @param ccateg a number greater than 1 (default: 1), proportionality factor
#'   for  the height of the categories.
#' @param propfactorequi .
#' @param cequi a number greater than 1 (default: 1), proportionality factor
#'   for  the height of the categories.
#' @param categtable .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$hists} \tab \tab \tab \tab \tab an array of groups \cr
#'   \code{results$categhist$categplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$categhist$categtable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
a4histrograms <- function(
    data,
    deps,
    categvar,
    previewplot = FALSE,
    previewtable = FALSE,
    equitable = FALSE,
    checkboxequi = FALSE,
    equibins = 10,
    checkboxcateg = FALSE,
    breakValues = "1,2,3",
    propfactorcateg = FALSE,
    ccateg = 1,
    propfactorequi = FALSE,
    cequi = 1,
    categtable = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("a4histrograms requires jmvcore to be installed (restart may be required)")

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(categvar)) categvar <- jmvcore::resolveQuo(jmvcore::enquo(categvar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(categvar), categvar, NULL))


    options <- a4histrogramsOptions$new(
        deps = deps,
        categvar = categvar,
        previewplot = previewplot,
        previewtable = previewtable,
        equitable = equitable,
        checkboxequi = checkboxequi,
        equibins = equibins,
        checkboxcateg = checkboxcateg,
        breakValues = breakValues,
        propfactorcateg = propfactorcateg,
        ccateg = ccateg,
        propfactorequi = propfactorequi,
        cequi = cequi,
        categtable = categtable)

    analysis <- a4histrogramsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

