
# This file is automatically generated, you probably don't want to edit this

a5concentrationmeasuresOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a5concentrationmeasuresOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            group = NULL,
            plotby = NULL,
            Tab = FALSE,
            Lorenz = FALSE,
            Gini = FALSE,
            norm = FALSE,
            Herf = FALSE, ...) {

            super$initialize(
                package="jamoviRWTH",
                name="a5concentrationmeasures",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                permitted=list(
                    "factor"),
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..plotby <- jmvcore::OptionVariable$new(
                "plotby",
                plotby,
                permitted=list(
                    "factor"),
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..Tab <- jmvcore::OptionBool$new(
                "Tab",
                Tab,
                default=FALSE)
            private$..Lorenz <- jmvcore::OptionBool$new(
                "Lorenz",
                Lorenz,
                default=FALSE)
            private$..Gini <- jmvcore::OptionBool$new(
                "Gini",
                Gini,
                default=FALSE)
            private$..norm <- jmvcore::OptionBool$new(
                "norm",
                norm,
                default=FALSE)
            private$..Herf <- jmvcore::OptionBool$new(
                "Herf",
                Herf,
                default=FALSE)

            self$.addOption(private$..var)
            self$.addOption(private$..group)
            self$.addOption(private$..plotby)
            self$.addOption(private$..Tab)
            self$.addOption(private$..Lorenz)
            self$.addOption(private$..Gini)
            self$.addOption(private$..norm)
            self$.addOption(private$..Herf)
        }),
    active = list(
        var = function() private$..var$value,
        group = function() private$..group$value,
        plotby = function() private$..plotby$value,
        Tab = function() private$..Tab$value,
        Lorenz = function() private$..Lorenz$value,
        Gini = function() private$..Gini$value,
        norm = function() private$..norm$value,
        Herf = function() private$..Herf$value),
    private = list(
        ..var = NA,
        ..group = NA,
        ..plotby = NA,
        ..Tab = NA,
        ..Lorenz = NA,
        ..Gini = NA,
        ..norm = NA,
        ..Herf = NA)
)

a5concentrationmeasuresResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a5concentrationmeasuresResults",
    inherit = jmvcore::Group,
    active = list(
        Tabdata = function() private$.items[["Tabdata"]],
        Lor = function() private$.items[["Lor"]],
        coeff = function() private$.items[["coeff"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Measures of Concentration (A5)")
            self$add(jmvcore::Table$new(
                options=options,
                name="Tabdata",
                title="Data",
                visible="(Tab & !is.null(var))",
                columns=list()))
            self$add(jmvcore::Image$new(
                options=options,
                name="Lor",
                title="Lorenz curve",
                visible="(Lorenz & !is.null(var))",
                renderFun=".plot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="coeff",
                title="Measures of concentration",
                visible="(Gini || norm || Herf)",
                rows=0,
                columns=list(
                    list(
                        `name`="Group", 
                        `type`="text", 
                        `visible`="(group)"),
                    list(
                        `name`="Gini", 
                        `title`="Gini's ratio", 
                        `type`="number", 
                        `visible`="(Gini)"),
                    list(
                        `name`="normalized", 
                        `title`="normalized Gini's ratio", 
                        `type`="number", 
                        `visible`="(norm)"),
                    list(
                        `name`="Herfin", 
                        `title`="Herfindahl index", 
                        `type`="number", 
                        `visible`="(Herf)"))))}))

a5concentrationmeasuresBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a5concentrationmeasuresBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "a5concentrationmeasures",
                version = c(1,0,0),
                options = options,
                results = a5concentrationmeasuresResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Measures of Concentration (A5)
#'
#' 
#' @param data .
#' @param var .
#' @param group .
#' @param plotby .
#' @param Tab .
#' @param Lorenz .
#' @param Gini .
#' @param norm .
#' @param Herf .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$Tabdata} \tab \tab \tab \tab \tab a table of data \cr
#'   \code{results$Lor} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$coeff} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$Tabdata$asDF}
#'
#' \code{as.data.frame(results$Tabdata)}
#'
#' @export
a5concentrationmeasures <- function(
    data,
    var,
    group,
    plotby,
    Tab = FALSE,
    Lorenz = FALSE,
    Gini = FALSE,
    norm = FALSE,
    Herf = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("a5concentrationmeasures requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if ( ! missing(plotby)) plotby <- jmvcore::resolveQuo(jmvcore::enquo(plotby))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL),
            `if`( ! missing(group), group, NULL),
            `if`( ! missing(plotby), plotby, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in plotby) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- a5concentrationmeasuresOptions$new(
        var = var,
        group = group,
        plotby = plotby,
        Tab = Tab,
        Lorenz = Lorenz,
        Gini = Gini,
        norm = norm,
        Herf = Herf)

    analysis <- a5concentrationmeasuresClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

