
# This file is automatically generated, you probably don't want to edit this

a6indexnumbersOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a6indexnumbersOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            k = NULL,
            basket0 = NULL,
            price0 = NULL,
            baskett = NULL,
            pricet = NULL,
            plas = FALSE,
            ppaa = FALSE,
            pfi = FALSE,
            qlas = FALSE,
            qpaa = FALSE,
            qfi = FALSE,
            val = FALSE,
            valBask = FALSE, ...) {

            super$initialize(
                package="jamoviRWTH",
                name="a6indexnumbers",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..indexnum <- jmvcore::OptionOutput$new(
                "indexnum")
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                min=0)
            private$..growthfac <- jmvcore::OptionOutput$new(
                "growthfac")
            private$..growthrate <- jmvcore::OptionOutput$new(
                "growthrate")
            private$..basket0 <- jmvcore::OptionVariable$new(
                "basket0",
                basket0,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..price0 <- jmvcore::OptionVariable$new(
                "price0",
                price0,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..baskett <- jmvcore::OptionVariable$new(
                "baskett",
                baskett,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..pricet <- jmvcore::OptionVariable$new(
                "pricet",
                pricet,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..plas <- jmvcore::OptionBool$new(
                "plas",
                plas,
                default=FALSE)
            private$..ppaa <- jmvcore::OptionBool$new(
                "ppaa",
                ppaa,
                default=FALSE)
            private$..pfi <- jmvcore::OptionBool$new(
                "pfi",
                pfi,
                default=FALSE)
            private$..qlas <- jmvcore::OptionBool$new(
                "qlas",
                qlas,
                default=FALSE)
            private$..qpaa <- jmvcore::OptionBool$new(
                "qpaa",
                qpaa,
                default=FALSE)
            private$..qfi <- jmvcore::OptionBool$new(
                "qfi",
                qfi,
                default=FALSE)
            private$..val <- jmvcore::OptionBool$new(
                "val",
                val,
                default=FALSE)
            private$..valBask <- jmvcore::OptionBool$new(
                "valBask",
                valBask,
                default=FALSE)

            self$.addOption(private$..var)
            self$.addOption(private$..indexnum)
            self$.addOption(private$..k)
            self$.addOption(private$..growthfac)
            self$.addOption(private$..growthrate)
            self$.addOption(private$..basket0)
            self$.addOption(private$..price0)
            self$.addOption(private$..baskett)
            self$.addOption(private$..pricet)
            self$.addOption(private$..plas)
            self$.addOption(private$..ppaa)
            self$.addOption(private$..pfi)
            self$.addOption(private$..qlas)
            self$.addOption(private$..qpaa)
            self$.addOption(private$..qfi)
            self$.addOption(private$..val)
            self$.addOption(private$..valBask)
        }),
    active = list(
        var = function() private$..var$value,
        indexnum = function() private$..indexnum$value,
        k = function() private$..k$value,
        growthfac = function() private$..growthfac$value,
        growthrate = function() private$..growthrate$value,
        basket0 = function() private$..basket0$value,
        price0 = function() private$..price0$value,
        baskett = function() private$..baskett$value,
        pricet = function() private$..pricet$value,
        plas = function() private$..plas$value,
        ppaa = function() private$..ppaa$value,
        pfi = function() private$..pfi$value,
        qlas = function() private$..qlas$value,
        qpaa = function() private$..qpaa$value,
        qfi = function() private$..qfi$value,
        val = function() private$..val$value,
        valBask = function() private$..valBask$value),
    private = list(
        ..var = NA,
        ..indexnum = NA,
        ..k = NA,
        ..growthfac = NA,
        ..growthrate = NA,
        ..basket0 = NA,
        ..price0 = NA,
        ..baskett = NA,
        ..pricet = NA,
        ..plas = NA,
        ..ppaa = NA,
        ..pfi = NA,
        ..qlas = NA,
        ..qpaa = NA,
        ..qfi = NA,
        ..val = NA,
        ..valBask = NA)
)

a6indexnumbersResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a6indexnumbersResults",
    inherit = jmvcore::Group,
    active = list(
        indexnum = function() private$.items[["indexnum"]],
        growthfac = function() private$.items[["growthfac"]],
        growthrate = function() private$.items[["growthrate"]],
        Indices = function() private$.items[["Indices"]],
        WW = function() private$.items[["WW"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Index Numbers (A6)")
            self$add(jmvcore::Output$new(
                options=options,
                name="indexnum",
                title="Index number",
                varTitle="Index Number",
                varDescription="Computed index number",
                measureType="continuous"))
            self$add(jmvcore::Output$new(
                options=options,
                name="growthfac",
                title="Growth factor",
                varTitle="Growth factor",
                varDescription="Computed growth factor",
                measureType="continuous"))
            self$add(jmvcore::Output$new(
                options=options,
                name="growthrate",
                title="Growth rate",
                varTitle="Grwoth rate",
                varDescription="Computed growth rate",
                measureType="continuous"))
            self$add(jmvcore::Table$new(
                options=options,
                name="Indices",
                title="Indices",
                visible="(plas && !is.null(basket0) && !is.null(price0) && !is.null(baskett) && !is.null(pricet) || ppaa && !is.null(basket0) && !is.null(price0) && !is.null(baskett) && !is.null(pricet) || pfi && !is.null(basket0) && !is.null(price0) && !is.null(baskett) && !is.null(pricet) || qlas && !is.null(basket0) && !is.null(price0) && !is.null(baskett) && !is.null(pricet) || qpaa && !is.null(basket0) && !is.null(price0) && !is.null(baskett) && !is.null(pricet) || qfi && !is.null(basket0) && !is.null(price0) && !is.null(baskett) && !is.null(pricet) || val && !is.null(basket0) && !is.null(price0) && !is.null(baskett) && !is.null(pricet))",
                rows=0,
                columns=list(
                    list(
                        `name`="plas", 
                        `title`="Price index Laspeyres", 
                        `type`="number", 
                        `visible`="(plas)"),
                    list(
                        `name`="ppaa", 
                        `title`="Price index Paasche", 
                        `type`="number", 
                        `visible`="(ppaa)"),
                    list(
                        `name`="pfi", 
                        `title`="Price index Fisher", 
                        `type`="number", 
                        `visible`="(pfi)"),
                    list(
                        `name`="qlas", 
                        `title`="Quantity index Laspeyres", 
                        `type`="number", 
                        `visible`="(qlas)"),
                    list(
                        `name`="qpaa", 
                        `title`="Quantity index Paasche", 
                        `type`="number", 
                        `visible`="(qpaa)"),
                    list(
                        `name`="qfi", 
                        `title`="Quantity index Fisher", 
                        `type`="number", 
                        `visible`="(qfi)"),
                    list(
                        `name`="val", 
                        `title`="Value index", 
                        `type`="number", 
                        `visible`="(val)"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="WW",
                title="Value of the baskets",
                visible="(valBask && !is.null(basket0) && !is.null(price0) && !is.null(baskett) && !is.null(pricet))"))}))

a6indexnumbersBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a6indexnumbersBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "a6indexnumbers",
                version = c(1,0,0),
                options = options,
                results = a6indexnumbersResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Index Numbers (A6)
#'
#' 
#' @param data .
#' @param var .
#' @param k .
#' @param basket0 .
#' @param price0 .
#' @param baskett .
#' @param pricet .
#' @param plas .
#' @param ppaa .
#' @param pfi .
#' @param qlas .
#' @param qpaa .
#' @param qfi .
#' @param val .
#' @param valBask .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$indexnum} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$growthfac} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$growthrate} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$Indices} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$WW} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$Indices$asDF}
#'
#' \code{as.data.frame(results$Indices)}
#'
#' @export
a6indexnumbers <- function(
    data,
    var,
    k,
    basket0,
    price0,
    baskett,
    pricet,
    plas = FALSE,
    ppaa = FALSE,
    pfi = FALSE,
    qlas = FALSE,
    qpaa = FALSE,
    qfi = FALSE,
    val = FALSE,
    valBask = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("a6indexnumbers requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if ( ! missing(basket0)) basket0 <- jmvcore::resolveQuo(jmvcore::enquo(basket0))
    if ( ! missing(price0)) price0 <- jmvcore::resolveQuo(jmvcore::enquo(price0))
    if ( ! missing(baskett)) baskett <- jmvcore::resolveQuo(jmvcore::enquo(baskett))
    if ( ! missing(pricet)) pricet <- jmvcore::resolveQuo(jmvcore::enquo(pricet))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL),
            `if`( ! missing(basket0), basket0, NULL),
            `if`( ! missing(price0), price0, NULL),
            `if`( ! missing(baskett), baskett, NULL),
            `if`( ! missing(pricet), pricet, NULL))


    options <- a6indexnumbersOptions$new(
        var = var,
        k = k,
        basket0 = basket0,
        price0 = price0,
        baskett = baskett,
        pricet = pricet,
        plas = plas,
        ppaa = ppaa,
        pfi = pfi,
        qlas = qlas,
        qpaa = qpaa,
        qfi = qfi,
        val = val,
        valBask = valBask)

    analysis <- a6indexnumbersClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

