
# This file is automatically generated, you probably don't want to edit this

a7correlationmeasuresOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a7correlationmeasuresOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            nominalcont1 = NULL,
            nominalcont2 = NULL,
            contCounts = NULL,
            nominal1 = NULL,
            nominal2 = NULL,
            metric1 = NULL,
            metric2 = NULL,
            ordinal1 = NULL,
            ordinal2 = NULL,
            cont_abs_table = FALSE,
            cont_rel_table = FALSE,
            cont_row_table = FALSE,
            cont_col_table = FALSE,
            cont_chi2 = FALSE,
            cont_Ccor = FALSE,
            cont_Cstern = FALSE,
            nominal_abs_table = FALSE,
            nominal_rel_table = FALSE,
            nominal_row_table = FALSE,
            nominal_col_table = FALSE,
            nominal_chi2 = FALSE,
            nominal_Ccor = FALSE,
            nominal_Cstern = FALSE,
            ordinal_spearman = FALSE,
            metric_empKov = FALSE,
            metric_bpKor = FALSE,
            metric_streu = FALSE, ...) {

            super$initialize(
                package="jamoviRWTH",
                name="a7correlationmeasures",
                requiresData=TRUE,
                ...)

            private$..nominalcont1 <- jmvcore::OptionVariable$new(
                "nominalcont1",
                nominalcont1,
                permitted=list(
                    "factor",
                    "id"),
                suggested=list(
                    "nominal"))
            private$..nominalcont2 <- jmvcore::OptionVariable$new(
                "nominalcont2",
                nominalcont2,
                permitted=list(
                    "factor",
                    "id"),
                suggested=list(
                    "nominal"))
            private$..contCounts <- jmvcore::OptionVariable$new(
                "contCounts",
                contCounts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nominal1 <- jmvcore::OptionVariable$new(
                "nominal1",
                nominal1,
                permitted=list(
                    "factor",
                    "id"),
                suggested=list(
                    "nominal"))
            private$..nominal2 <- jmvcore::OptionVariable$new(
                "nominal2",
                nominal2,
                permitted=list(
                    "factor",
                    "id"),
                suggested=list(
                    "nominal"))
            private$..metric1 <- jmvcore::OptionVariable$new(
                "metric1",
                metric1,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..metric2 <- jmvcore::OptionVariable$new(
                "metric2",
                metric2,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..ordinal1 <- jmvcore::OptionVariable$new(
                "ordinal1",
                ordinal1,
                permitted=list(
                    "factor",
                    "numeric"),
                suggested=list(
                    "ordinal",
                    "continuous"))
            private$..ordinal2 <- jmvcore::OptionVariable$new(
                "ordinal2",
                ordinal2,
                permitted=list(
                    "factor",
                    "numeric"),
                suggested=list(
                    "ordinal",
                    "continuous"))
            private$..cont_abs_table <- jmvcore::OptionBool$new(
                "cont_abs_table",
                cont_abs_table,
                default=FALSE)
            private$..cont_rel_table <- jmvcore::OptionBool$new(
                "cont_rel_table",
                cont_rel_table,
                default=FALSE)
            private$..cont_row_table <- jmvcore::OptionBool$new(
                "cont_row_table",
                cont_row_table,
                default=FALSE)
            private$..cont_col_table <- jmvcore::OptionBool$new(
                "cont_col_table",
                cont_col_table,
                default=FALSE)
            private$..cont_chi2 <- jmvcore::OptionBool$new(
                "cont_chi2",
                cont_chi2,
                default=FALSE)
            private$..cont_Ccor <- jmvcore::OptionBool$new(
                "cont_Ccor",
                cont_Ccor,
                default=FALSE)
            private$..cont_Cstern <- jmvcore::OptionBool$new(
                "cont_Cstern",
                cont_Cstern,
                default=FALSE)
            private$..nominal_abs_table <- jmvcore::OptionBool$new(
                "nominal_abs_table",
                nominal_abs_table,
                default=FALSE)
            private$..nominal_rel_table <- jmvcore::OptionBool$new(
                "nominal_rel_table",
                nominal_rel_table,
                default=FALSE)
            private$..nominal_row_table <- jmvcore::OptionBool$new(
                "nominal_row_table",
                nominal_row_table,
                default=FALSE)
            private$..nominal_col_table <- jmvcore::OptionBool$new(
                "nominal_col_table",
                nominal_col_table,
                default=FALSE)
            private$..nominal_chi2 <- jmvcore::OptionBool$new(
                "nominal_chi2",
                nominal_chi2,
                default=FALSE)
            private$..nominal_Ccor <- jmvcore::OptionBool$new(
                "nominal_Ccor",
                nominal_Ccor,
                default=FALSE)
            private$..nominal_Cstern <- jmvcore::OptionBool$new(
                "nominal_Cstern",
                nominal_Cstern,
                default=FALSE)
            private$..ordinal_spearman <- jmvcore::OptionBool$new(
                "ordinal_spearman",
                ordinal_spearman,
                default=FALSE)
            private$..metric_empKov <- jmvcore::OptionBool$new(
                "metric_empKov",
                metric_empKov,
                default=FALSE)
            private$..metric_bpKor <- jmvcore::OptionBool$new(
                "metric_bpKor",
                metric_bpKor,
                default=FALSE)
            private$..metric_streu <- jmvcore::OptionBool$new(
                "metric_streu",
                metric_streu,
                default=FALSE)

            self$.addOption(private$..nominalcont1)
            self$.addOption(private$..nominalcont2)
            self$.addOption(private$..contCounts)
            self$.addOption(private$..nominal1)
            self$.addOption(private$..nominal2)
            self$.addOption(private$..metric1)
            self$.addOption(private$..metric2)
            self$.addOption(private$..ordinal1)
            self$.addOption(private$..ordinal2)
            self$.addOption(private$..cont_abs_table)
            self$.addOption(private$..cont_rel_table)
            self$.addOption(private$..cont_row_table)
            self$.addOption(private$..cont_col_table)
            self$.addOption(private$..cont_chi2)
            self$.addOption(private$..cont_Ccor)
            self$.addOption(private$..cont_Cstern)
            self$.addOption(private$..nominal_abs_table)
            self$.addOption(private$..nominal_rel_table)
            self$.addOption(private$..nominal_row_table)
            self$.addOption(private$..nominal_col_table)
            self$.addOption(private$..nominal_chi2)
            self$.addOption(private$..nominal_Ccor)
            self$.addOption(private$..nominal_Cstern)
            self$.addOption(private$..ordinal_spearman)
            self$.addOption(private$..metric_empKov)
            self$.addOption(private$..metric_bpKor)
            self$.addOption(private$..metric_streu)
        }),
    active = list(
        nominalcont1 = function() private$..nominalcont1$value,
        nominalcont2 = function() private$..nominalcont2$value,
        contCounts = function() private$..contCounts$value,
        nominal1 = function() private$..nominal1$value,
        nominal2 = function() private$..nominal2$value,
        metric1 = function() private$..metric1$value,
        metric2 = function() private$..metric2$value,
        ordinal1 = function() private$..ordinal1$value,
        ordinal2 = function() private$..ordinal2$value,
        cont_abs_table = function() private$..cont_abs_table$value,
        cont_rel_table = function() private$..cont_rel_table$value,
        cont_row_table = function() private$..cont_row_table$value,
        cont_col_table = function() private$..cont_col_table$value,
        cont_chi2 = function() private$..cont_chi2$value,
        cont_Ccor = function() private$..cont_Ccor$value,
        cont_Cstern = function() private$..cont_Cstern$value,
        nominal_abs_table = function() private$..nominal_abs_table$value,
        nominal_rel_table = function() private$..nominal_rel_table$value,
        nominal_row_table = function() private$..nominal_row_table$value,
        nominal_col_table = function() private$..nominal_col_table$value,
        nominal_chi2 = function() private$..nominal_chi2$value,
        nominal_Ccor = function() private$..nominal_Ccor$value,
        nominal_Cstern = function() private$..nominal_Cstern$value,
        ordinal_spearman = function() private$..ordinal_spearman$value,
        metric_empKov = function() private$..metric_empKov$value,
        metric_bpKor = function() private$..metric_bpKor$value,
        metric_streu = function() private$..metric_streu$value),
    private = list(
        ..nominalcont1 = NA,
        ..nominalcont2 = NA,
        ..contCounts = NA,
        ..nominal1 = NA,
        ..nominal2 = NA,
        ..metric1 = NA,
        ..metric2 = NA,
        ..ordinal1 = NA,
        ..ordinal2 = NA,
        ..cont_abs_table = NA,
        ..cont_rel_table = NA,
        ..cont_row_table = NA,
        ..cont_col_table = NA,
        ..cont_chi2 = NA,
        ..cont_Ccor = NA,
        ..cont_Cstern = NA,
        ..nominal_abs_table = NA,
        ..nominal_rel_table = NA,
        ..nominal_row_table = NA,
        ..nominal_col_table = NA,
        ..nominal_chi2 = NA,
        ..nominal_Ccor = NA,
        ..nominal_Cstern = NA,
        ..ordinal_spearman = NA,
        ..metric_empKov = NA,
        ..metric_bpKor = NA,
        ..metric_streu = NA)
)

a7correlationmeasuresResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a7correlationmeasuresResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        cont_abs_table = function() private$.items[["cont_abs_table"]],
        cont_rel_table = function() private$.items[["cont_rel_table"]],
        cont_row_table = function() private$.items[["cont_row_table"]],
        cont_col_table = function() private$.items[["cont_col_table"]],
        cont_table = function() private$.items[["cont_table"]],
        nominal_abs_table = function() private$.items[["nominal_abs_table"]],
        nominal_rel_table = function() private$.items[["nominal_rel_table"]],
        nominal_row_table = function() private$.items[["nominal_row_table"]],
        nominal_col_table = function() private$.items[["nominal_col_table"]],
        nominal_table = function() private$.items[["nominal_table"]],
        metric_table = function() private$.items[["metric_table"]],
        scatterplot = function() private$.items[["scatterplot"]],
        ordinal_table = function() private$.items[["ordinal_table"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Measures of Correlation and Dependence (A7)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Measures of Correlation and Dependence"))
            self$add(jmvcore::Table$new(
                options=options,
                name="cont_abs_table",
                title="Contingency table with absolute frequencies",
                visible="(cont_abs_table && !is.null(nominalcont1) && !is.null(nominalcont2) && !is.null(contCounts))",
                columns=list(),
                clearWith=list(
                    "nominalcont1",
                    "nominalcont2",
                    "contCounts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="cont_rel_table",
                title="Contingency table with relative frequencies",
                visible="(cont_rel_table && !is.null(nominalcont1) && !is.null(nominalcont2) && !is.null(contCounts))",
                columns=list(),
                clearWith=list(
                    "nominalcont1",
                    "nominalcont2",
                    "contCounts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="cont_row_table",
                title="Conditional contingency table on row",
                visible="(cont_row_table && !is.null(nominalcont1) && !is.null(nominalcont2) && !is.null(contCounts))",
                columns=list(),
                clearWith=list(
                    "nominalcont1",
                    "nominalcont2",
                    "contCounts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="cont_col_table",
                title="Conditional contingency table on column",
                visible="(cont_col_table && !is.null(nominalcont1) && !is.null(nominalcont2) && !is.null(contCounts))",
                columns=list(),
                clearWith=list(
                    "nominalcont1",
                    "nominalcont2",
                    "contCounts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="cont_table",
                title="Measures of Correlation and Dependence for Categorical Data",
                visible="(cont_chi2 || cont_Ccor || cont_Cstern)",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="chi.2", 
                        `title`="\u03C7\u00B2", 
                        `type`="number", 
                        `visible`="(cont_chi2)"),
                    list(
                        `name`="C", 
                        `title`="C", 
                        `type`="number", 
                        `visible`="(cont_Ccor)"),
                    list(
                        `name`="CStern", 
                        `title`="C*", 
                        `type`="number", 
                        `visible`="(cont_Cstern)")),
                clearWith=list(
                    "nominalcont1",
                    "nominalcont2",
                    "contCounts")))
            self$add(jmvcore::Table$new(
                options=options,
                name="nominal_abs_table",
                title="Contingency table with absolute frequencies",
                visible="(nominal_abs_table && !is.null(nominal1) && !is.null(nominal2))",
                columns=list(),
                clearWith=list(
                    "nominal1",
                    "nominal2")))
            self$add(jmvcore::Table$new(
                options=options,
                name="nominal_rel_table",
                title="Contingency table with relative frequencies",
                visible="(nominal_rel_table && !is.null(nominal1) && !is.null(nominal2))",
                columns=list(),
                clearWith=list(
                    "nominal1",
                    "nominal2")))
            self$add(jmvcore::Table$new(
                options=options,
                name="nominal_row_table",
                title="Conditional contingency table on row",
                visible="(nominal_row_table && !is.null(nominal1) && !is.null(nominal2))",
                columns=list(),
                clearWith=list(
                    "nominal1",
                    "nominal2")))
            self$add(jmvcore::Table$new(
                options=options,
                name="nominal_col_table",
                title="Conditional contingency table on column",
                visible="(nominal_col_table && !is.null(nominal1) && !is.null(nominal2))",
                columns=list(),
                clearWith=list(
                    "nominal1",
                    "nominal2")))
            self$add(jmvcore::Table$new(
                options=options,
                name="nominal_table",
                title="Measures of Correlation and Dependence for Categorical Data",
                visible="(nominal_chi2 || nominal_Ccor || nominal_Cstern)",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="chi.2", 
                        `title`="\u03C7\u00B2", 
                        `type`="number", 
                        `visible`="(nominal_chi2)"),
                    list(
                        `name`="C", 
                        `title`="C", 
                        `type`="number", 
                        `visible`="(nominal_Ccor)"),
                    list(
                        `name`="CStern", 
                        `title`="C*", 
                        `type`="number", 
                        `visible`="(nominal_Cstern)")),
                clearWith=list(
                    "nominal1",
                    "nominal2")))
            self$add(jmvcore::Table$new(
                options=options,
                name="metric_table",
                title="Measures of Correlation and Dependence for Metric Data",
                visible="(metric_empKov || metric_bpKor)",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="sxy", 
                        `title`="s\u2093\u1D67", 
                        `type`="number", 
                        `visible`="(metric_empKov)"),
                    list(
                        `name`="r", 
                        `type`="number", 
                        `visible`="(metric_bpKor)")),
                clearWith=list(
                    "metric1",
                    "metric2")))
            self$add(jmvcore::Image$new(
                options=options,
                name="scatterplot",
                title="Scatterplot",
                visible="(metric_streu)",
                renderFun=".scatplot",
                clearWith=list(
                    "metric1",
                    "metric2")))
            self$add(jmvcore::Table$new(
                options=options,
                name="ordinal_table",
                title="Measures of Correlation and Dependence for Ordinal Data",
                visible="(ordinal_spearman)",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="rSP", 
                        `title`="r\u209B\u209A", 
                        `type`="number", 
                        `visible`="(ordinal_spearman)")),
                clearWith=list(
                    "ordinal1",
                    "ordinal2")))}))

a7correlationmeasuresBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a7correlationmeasuresBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "a7correlationmeasures",
                version = c(1,0,0),
                options = options,
                results = a7correlationmeasuresResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Measures of Correlation and Dependence (A7)
#'
#' 
#' @param data .
#' @param nominalcont1 .
#' @param nominalcont2 .
#' @param contCounts .
#' @param nominal1 .
#' @param nominal2 .
#' @param metric1 .
#' @param metric2 .
#' @param ordinal1 .
#' @param ordinal2 .
#' @param cont_abs_table .
#' @param cont_rel_table .
#' @param cont_row_table .
#' @param cont_col_table .
#' @param cont_chi2 .
#' @param cont_Ccor .
#' @param cont_Cstern .
#' @param nominal_abs_table .
#' @param nominal_rel_table .
#' @param nominal_row_table .
#' @param nominal_col_table .
#' @param nominal_chi2 .
#' @param nominal_Ccor .
#' @param nominal_Cstern .
#' @param ordinal_spearman .
#' @param metric_empKov .
#' @param metric_bpKor .
#' @param metric_streu .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$cont_abs_table} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$cont_rel_table} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$cont_row_table} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$cont_col_table} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$cont_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$nominal_abs_table} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$nominal_rel_table} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$nominal_row_table} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$nominal_col_table} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$nominal_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$metric_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$scatterplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ordinal_table} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$cont_abs_table$asDF}
#'
#' \code{as.data.frame(results$cont_abs_table)}
#'
#' @export
a7correlationmeasures <- function(
    data,
    nominalcont1,
    nominalcont2,
    contCounts,
    nominal1,
    nominal2,
    metric1,
    metric2,
    ordinal1,
    ordinal2,
    cont_abs_table = FALSE,
    cont_rel_table = FALSE,
    cont_row_table = FALSE,
    cont_col_table = FALSE,
    cont_chi2 = FALSE,
    cont_Ccor = FALSE,
    cont_Cstern = FALSE,
    nominal_abs_table = FALSE,
    nominal_rel_table = FALSE,
    nominal_row_table = FALSE,
    nominal_col_table = FALSE,
    nominal_chi2 = FALSE,
    nominal_Ccor = FALSE,
    nominal_Cstern = FALSE,
    ordinal_spearman = FALSE,
    metric_empKov = FALSE,
    metric_bpKor = FALSE,
    metric_streu = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("a7correlationmeasures requires jmvcore to be installed (restart may be required)")

    if ( ! missing(nominalcont1)) nominalcont1 <- jmvcore::resolveQuo(jmvcore::enquo(nominalcont1))
    if ( ! missing(nominalcont2)) nominalcont2 <- jmvcore::resolveQuo(jmvcore::enquo(nominalcont2))
    if ( ! missing(contCounts)) contCounts <- jmvcore::resolveQuo(jmvcore::enquo(contCounts))
    if ( ! missing(nominal1)) nominal1 <- jmvcore::resolveQuo(jmvcore::enquo(nominal1))
    if ( ! missing(nominal2)) nominal2 <- jmvcore::resolveQuo(jmvcore::enquo(nominal2))
    if ( ! missing(metric1)) metric1 <- jmvcore::resolveQuo(jmvcore::enquo(metric1))
    if ( ! missing(metric2)) metric2 <- jmvcore::resolveQuo(jmvcore::enquo(metric2))
    if ( ! missing(ordinal1)) ordinal1 <- jmvcore::resolveQuo(jmvcore::enquo(ordinal1))
    if ( ! missing(ordinal2)) ordinal2 <- jmvcore::resolveQuo(jmvcore::enquo(ordinal2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(nominalcont1), nominalcont1, NULL),
            `if`( ! missing(nominalcont2), nominalcont2, NULL),
            `if`( ! missing(contCounts), contCounts, NULL),
            `if`( ! missing(nominal1), nominal1, NULL),
            `if`( ! missing(nominal2), nominal2, NULL),
            `if`( ! missing(metric1), metric1, NULL),
            `if`( ! missing(metric2), metric2, NULL),
            `if`( ! missing(ordinal1), ordinal1, NULL),
            `if`( ! missing(ordinal2), ordinal2, NULL))


    options <- a7correlationmeasuresOptions$new(
        nominalcont1 = nominalcont1,
        nominalcont2 = nominalcont2,
        contCounts = contCounts,
        nominal1 = nominal1,
        nominal2 = nominal2,
        metric1 = metric1,
        metric2 = metric2,
        ordinal1 = ordinal1,
        ordinal2 = ordinal2,
        cont_abs_table = cont_abs_table,
        cont_rel_table = cont_rel_table,
        cont_row_table = cont_row_table,
        cont_col_table = cont_col_table,
        cont_chi2 = cont_chi2,
        cont_Ccor = cont_Ccor,
        cont_Cstern = cont_Cstern,
        nominal_abs_table = nominal_abs_table,
        nominal_rel_table = nominal_rel_table,
        nominal_row_table = nominal_row_table,
        nominal_col_table = nominal_col_table,
        nominal_chi2 = nominal_chi2,
        nominal_Ccor = nominal_Ccor,
        nominal_Cstern = nominal_Cstern,
        ordinal_spearman = ordinal_spearman,
        metric_empKov = metric_empKov,
        metric_bpKor = metric_bpKor,
        metric_streu = metric_streu)

    analysis <- a7correlationmeasuresClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

