
# This file is automatically generated, you probably don't want to edit this

a8linearregressionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a8linearregressionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            covariate = NULL,
            linReg = FALSE,
            linRegIntercept = FALSE,
            interceptvalue = 0,
            bpKor = FALSE,
            B = FALSE,
            resPlot = FALSE,
            normedresPlot = FALSE,
            scatter = FALSE,
            regplot = FALSE,
            regplotquad = FALSE,
            regplotpoly = FALSE,
            degree = 3,
            regplotlog = FALSE,
            pred = FALSE,
            predvalue = 1, ...) {

            super$initialize(
                package="jamoviRWTH",
                name="a8linearregression",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..covariate <- jmvcore::OptionVariable$new(
                "covariate",
                covariate,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..linReg <- jmvcore::OptionBool$new(
                "linReg",
                linReg,
                default=FALSE)
            private$..linRegIntercept <- jmvcore::OptionBool$new(
                "linRegIntercept",
                linRegIntercept,
                default=FALSE)
            private$..interceptvalue <- jmvcore::OptionNumber$new(
                "interceptvalue",
                interceptvalue,
                default=0)
            private$..bpKor <- jmvcore::OptionBool$new(
                "bpKor",
                bpKor,
                default=FALSE)
            private$..B <- jmvcore::OptionBool$new(
                "B",
                B,
                default=FALSE)
            private$..resPlot <- jmvcore::OptionBool$new(
                "resPlot",
                resPlot,
                default=FALSE)
            private$..normedresPlot <- jmvcore::OptionBool$new(
                "normedresPlot",
                normedresPlot,
                default=FALSE)
            private$..scatter <- jmvcore::OptionBool$new(
                "scatter",
                scatter,
                default=FALSE)
            private$..regplot <- jmvcore::OptionBool$new(
                "regplot",
                regplot,
                default=FALSE)
            private$..regplotquad <- jmvcore::OptionBool$new(
                "regplotquad",
                regplotquad,
                default=FALSE)
            private$..regplotpoly <- jmvcore::OptionBool$new(
                "regplotpoly",
                regplotpoly,
                default=FALSE)
            private$..degree <- jmvcore::OptionNumber$new(
                "degree",
                degree,
                min=1,
                default=3)
            private$..regplotlog <- jmvcore::OptionBool$new(
                "regplotlog",
                regplotlog,
                default=FALSE)
            private$..residsOV <- jmvcore::OptionOutput$new(
                "residsOV")
            private$..normedresidsOV <- jmvcore::OptionOutput$new(
                "normedresidsOV")
            private$..predictionsOV <- jmvcore::OptionOutput$new(
                "predictionsOV")
            private$..pred <- jmvcore::OptionBool$new(
                "pred",
                pred,
                default=FALSE)
            private$..predvalue <- jmvcore::OptionNumber$new(
                "predvalue",
                predvalue,
                min=0,
                default=1)

            self$.addOption(private$..var)
            self$.addOption(private$..covariate)
            self$.addOption(private$..linReg)
            self$.addOption(private$..linRegIntercept)
            self$.addOption(private$..interceptvalue)
            self$.addOption(private$..bpKor)
            self$.addOption(private$..B)
            self$.addOption(private$..resPlot)
            self$.addOption(private$..normedresPlot)
            self$.addOption(private$..scatter)
            self$.addOption(private$..regplot)
            self$.addOption(private$..regplotquad)
            self$.addOption(private$..regplotpoly)
            self$.addOption(private$..degree)
            self$.addOption(private$..regplotlog)
            self$.addOption(private$..residsOV)
            self$.addOption(private$..normedresidsOV)
            self$.addOption(private$..predictionsOV)
            self$.addOption(private$..pred)
            self$.addOption(private$..predvalue)
        }),
    active = list(
        var = function() private$..var$value,
        covariate = function() private$..covariate$value,
        linReg = function() private$..linReg$value,
        linRegIntercept = function() private$..linRegIntercept$value,
        interceptvalue = function() private$..interceptvalue$value,
        bpKor = function() private$..bpKor$value,
        B = function() private$..B$value,
        resPlot = function() private$..resPlot$value,
        normedresPlot = function() private$..normedresPlot$value,
        scatter = function() private$..scatter$value,
        regplot = function() private$..regplot$value,
        regplotquad = function() private$..regplotquad$value,
        regplotpoly = function() private$..regplotpoly$value,
        degree = function() private$..degree$value,
        regplotlog = function() private$..regplotlog$value,
        residsOV = function() private$..residsOV$value,
        normedresidsOV = function() private$..normedresidsOV$value,
        predictionsOV = function() private$..predictionsOV$value,
        pred = function() private$..pred$value,
        predvalue = function() private$..predvalue$value),
    private = list(
        ..var = NA,
        ..covariate = NA,
        ..linReg = NA,
        ..linRegIntercept = NA,
        ..interceptvalue = NA,
        ..bpKor = NA,
        ..B = NA,
        ..resPlot = NA,
        ..normedresPlot = NA,
        ..scatter = NA,
        ..regplot = NA,
        ..regplotquad = NA,
        ..regplotpoly = NA,
        ..degree = NA,
        ..regplotlog = NA,
        ..residsOV = NA,
        ..normedresidsOV = NA,
        ..predictionsOV = NA,
        ..pred = NA,
        ..predvalue = NA)
)

a8linearregressionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a8linearregressionResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        linreg = function() private$.items[["linreg"]],
        residsOV = function() private$.items[["residsOV"]],
        normedresidsOV = function() private$.items[["normedresidsOV"]],
        predictionsOV = function() private$.items[["predictionsOV"]],
        scatterplot = function() private$.items[["scatterplot"]],
        resplot = function() private$.items[["resplot"]],
        predtable = function() private$.items[["predtable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Regression Analysis (A8)")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Regression Analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="linreg",
                title="Linear Regression (least squares)",
                visible="(linReg || bpKor || B)",
                rows=0,
                columns=list(
                    list(
                        `name`="a_hat", 
                        `title`="\u00E2", 
                        `type`="number", 
                        `visible`="(linReg & !linRegIntercept)"),
                    list(
                        `name`="b_hat", 
                        `title`="b\u0302", 
                        `type`="number", 
                        `visible`="(linReg)"),
                    list(
                        `name`="r", 
                        `type`="number", 
                        `visible`="(bpKor)"),
                    list(
                        `name`="B", 
                        `type`="number", 
                        `visible`="(B)"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="residsOV",
                title="Residuals",
                varTitle="Residuals",
                varDescription="Residuals from linear regression",
                measureType="continuous"))
            self$add(jmvcore::Output$new(
                options=options,
                name="normedresidsOV",
                title="Normed residuals",
                varTitle="Normed residuals",
                varDescription="Normalized residuals from linear regression",
                measureType="continuous"))
            self$add(jmvcore::Output$new(
                options=options,
                name="predictionsOV",
                title="Predictions",
                varTitle="Predictions",
                varDescription="Predictions from linear regression",
                measureType="continuous"))
            self$add(jmvcore::Image$new(
                options=options,
                name="scatterplot",
                title="Scatterplot",
                visible="(scatter)",
                renderFun=".scatplot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="resplot",
                title="Plot of residuals",
                visible="(resPlot)",
                renderFun=".resplot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="predtable",
                title="Prediction of a value",
                visible="(pred)",
                rows=0,
                columns=list(
                    list(
                        `name`="xvalue", 
                        `title`="x"),
                    list(
                        `name`="prediction", 
                        `title`="Prediction"))))}))

a8linearregressionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a8linearregressionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "a8linearregression",
                version = c(1,0,0),
                options = options,
                results = a8linearregressionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Regression Analysis (A8)
#'
#' 
#' @param data .
#' @param var the dependent variables (not necessary when using a formula, see
#'   the examples)
#' @param covariate the grouping variable with two levels (not necessary when
#'   using a formula, see the examples)
#' @param linReg .
#' @param linRegIntercept .
#' @param interceptvalue .
#' @param bpKor .
#' @param B .
#' @param resPlot .
#' @param normedresPlot .
#' @param scatter .
#' @param regplot .
#' @param regplotquad .
#' @param regplotpoly .
#' @param degree .
#' @param regplotlog .
#' @param pred .
#' @param predvalue .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$linreg} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$residsOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$normedresidsOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$predictionsOV} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$scatterplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$resplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$predtable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$linreg$asDF}
#'
#' \code{as.data.frame(results$linreg)}
#'
#' @export
a8linearregression <- function(
    data,
    var,
    covariate,
    linReg = FALSE,
    linRegIntercept = FALSE,
    interceptvalue = 0,
    bpKor = FALSE,
    B = FALSE,
    resPlot = FALSE,
    normedresPlot = FALSE,
    scatter = FALSE,
    regplot = FALSE,
    regplotquad = FALSE,
    regplotpoly = FALSE,
    degree = 3,
    regplotlog = FALSE,
    pred = FALSE,
    predvalue = 1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("a8linearregression requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if ( ! missing(covariate)) covariate <- jmvcore::resolveQuo(jmvcore::enquo(covariate))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL),
            `if`( ! missing(covariate), covariate, NULL))


    options <- a8linearregressionOptions$new(
        var = var,
        covariate = covariate,
        linReg = linReg,
        linRegIntercept = linRegIntercept,
        interceptvalue = interceptvalue,
        bpKor = bpKor,
        B = B,
        resPlot = resPlot,
        normedresPlot = normedresPlot,
        scatter = scatter,
        regplot = regplot,
        regplotquad = regplotquad,
        regplotpoly = regplotpoly,
        degree = degree,
        regplotlog = regplotlog,
        pred = pred,
        predvalue = predvalue)

    analysis <- a8linearregressionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

