
# This file is automatically generated, you probably don't want to edit this

a9timeseriesanalysisOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a9timeseriesanalysisOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            time = NULL,
            runchart = FALSE,
            addest = FALSE,
            Ordnung = "2", ...) {

            super$initialize(
                package="jamoviRWTH",
                name="a9timeseriesanalysis",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..time <- jmvcore::OptionVariable$new(
                "time",
                time,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..runchart <- jmvcore::OptionBool$new(
                "runchart",
                runchart,
                default=FALSE)
            private$..addest <- jmvcore::OptionBool$new(
                "addest",
                addest,
                default=FALSE)
            private$..reg <- jmvcore::OptionOutput$new(
                "reg")
            private$..movavOS <- jmvcore::OptionOutput$new(
                "movavOS")
            private$..Ordnung <- jmvcore::OptionString$new(
                "Ordnung",
                Ordnung,
                default="2")
            private$..movavMS <- jmvcore::OptionOutput$new(
                "movavMS")

            self$.addOption(private$..var)
            self$.addOption(private$..time)
            self$.addOption(private$..runchart)
            self$.addOption(private$..addest)
            self$.addOption(private$..reg)
            self$.addOption(private$..movavOS)
            self$.addOption(private$..Ordnung)
            self$.addOption(private$..movavMS)
        }),
    active = list(
        var = function() private$..var$value,
        time = function() private$..time$value,
        runchart = function() private$..runchart$value,
        addest = function() private$..addest$value,
        reg = function() private$..reg$value,
        movavOS = function() private$..movavOS$value,
        Ordnung = function() private$..Ordnung$value,
        movavMS = function() private$..movavMS$value),
    private = list(
        ..var = NA,
        ..time = NA,
        ..runchart = NA,
        ..addest = NA,
        ..reg = NA,
        ..movavOS = NA,
        ..Ordnung = NA,
        ..movavMS = NA)
)

a9timeseriesanalysisResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a9timeseriesanalysisResults",
    inherit = jmvcore::Group,
    active = list(
        run = function() private$.items[["run"]],
        reg = function() private$.items[["reg"]],
        movavOS = function() private$.items[["movavOS"]],
        movavMS = function() private$.items[["movavMS"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Time Series Analysis (A9)")
            self$add(jmvcore::Image$new(
                options=options,
                name="run",
                title="Run chart",
                visible="(runchart & !is.null(var))",
                width=500,
                height=300,
                renderFun=".plot"))
            self$add(jmvcore::Output$new(
                options=options,
                name="reg",
                title="Regression",
                varTitle="y_hut reg",
                measureType="continuous"))
            self$add(jmvcore::Output$new(
                options=options,
                name="movavOS",
                title="gOS",
                varTitle="y_hut woS",
                measureType="continuous"))
            self$add(jmvcore::Output$new(
                options=options,
                name="movavMS",
                title="gMS",
                varTitle="y_hut wS",
                measureType="continuous"))}))

a9timeseriesanalysisBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "a9timeseriesanalysisBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "a9timeseriesanalysis",
                version = c(1,0,0),
                options = options,
                results = a9timeseriesanalysisResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Time Series Analysis (A9)
#'
#' 
#' @param data .
#' @param var .
#' @param time .
#' @param runchart .
#' @param addest .
#' @param Ordnung .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$run} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$reg} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$movavOS} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$movavMS} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' @export
a9timeseriesanalysis <- function(
    data,
    var,
    time,
    runchart = FALSE,
    addest = FALSE,
    Ordnung = "2") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("a9timeseriesanalysis requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if ( ! missing(time)) time <- jmvcore::resolveQuo(jmvcore::enquo(time))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL),
            `if`( ! missing(time), time, NULL))


    options <- a9timeseriesanalysisOptions$new(
        var = var,
        time = time,
        runchart = runchart,
        addest = addest,
        Ordnung = Ordnung)

    analysis <- a9timeseriesanalysisClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

