
# This file is automatically generated, you probably don't want to edit this

d3maximumlikelihoodOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d3maximumlikelihoodOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            var = NULL,
            bindistr = FALSE,
            geodistr = FALSE,
            podistr = FALSE,
            Ndistr = FALSE,
            expdistr = FALSE,
            Udistr = FALSE,
            pardistr = FALSE,
            powdistr = FALSE,
            variance = FALSE,
            mean = FALSE,
            mu = 0,
            expparameter = NULL,
            unifa = FALSE,
            a = 0,
            unifb = FALSE,
            b = 1, ...) {

            super$initialize(
                package="jamoviRWTH",
                name="d3maximumlikelihood",
                requiresData=TRUE,
                ...)

            private$..var <- jmvcore::OptionVariable$new(
                "var",
                var,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..bindistr <- jmvcore::OptionBool$new(
                "bindistr",
                bindistr,
                default=FALSE)
            private$..geodistr <- jmvcore::OptionBool$new(
                "geodistr",
                geodistr,
                default=FALSE)
            private$..podistr <- jmvcore::OptionBool$new(
                "podistr",
                podistr,
                default=FALSE)
            private$..Ndistr <- jmvcore::OptionBool$new(
                "Ndistr",
                Ndistr,
                default=FALSE)
            private$..expdistr <- jmvcore::OptionBool$new(
                "expdistr",
                expdistr,
                default=FALSE)
            private$..Udistr <- jmvcore::OptionBool$new(
                "Udistr",
                Udistr,
                default=FALSE)
            private$..pardistr <- jmvcore::OptionBool$new(
                "pardistr",
                pardistr,
                default=FALSE)
            private$..powdistr <- jmvcore::OptionBool$new(
                "powdistr",
                powdistr,
                default=FALSE)
            private$..variance <- jmvcore::OptionBool$new(
                "variance",
                variance,
                default=FALSE)
            private$..mean <- jmvcore::OptionBool$new(
                "mean",
                mean,
                default=FALSE)
            private$..mu <- jmvcore::OptionNumber$new(
                "mu",
                mu,
                default=0)
            private$..expparameter <- jmvcore::OptionList$new(
                "expparameter",
                expparameter,
                options=list(
                    "lambda",
                    "oneoverlambda"))
            private$..unifa <- jmvcore::OptionBool$new(
                "unifa",
                unifa,
                default=FALSE)
            private$..a <- jmvcore::OptionNumber$new(
                "a",
                a,
                default=0)
            private$..unifb <- jmvcore::OptionBool$new(
                "unifb",
                unifb,
                default=FALSE)
            private$..b <- jmvcore::OptionNumber$new(
                "b",
                b,
                default=1)

            self$.addOption(private$..var)
            self$.addOption(private$..bindistr)
            self$.addOption(private$..geodistr)
            self$.addOption(private$..podistr)
            self$.addOption(private$..Ndistr)
            self$.addOption(private$..expdistr)
            self$.addOption(private$..Udistr)
            self$.addOption(private$..pardistr)
            self$.addOption(private$..powdistr)
            self$.addOption(private$..variance)
            self$.addOption(private$..mean)
            self$.addOption(private$..mu)
            self$.addOption(private$..expparameter)
            self$.addOption(private$..unifa)
            self$.addOption(private$..a)
            self$.addOption(private$..unifb)
            self$.addOption(private$..b)
        }),
    active = list(
        var = function() private$..var$value,
        bindistr = function() private$..bindistr$value,
        geodistr = function() private$..geodistr$value,
        podistr = function() private$..podistr$value,
        Ndistr = function() private$..Ndistr$value,
        expdistr = function() private$..expdistr$value,
        Udistr = function() private$..Udistr$value,
        pardistr = function() private$..pardistr$value,
        powdistr = function() private$..powdistr$value,
        variance = function() private$..variance$value,
        mean = function() private$..mean$value,
        mu = function() private$..mu$value,
        expparameter = function() private$..expparameter$value,
        unifa = function() private$..unifa$value,
        a = function() private$..a$value,
        unifb = function() private$..unifb$value,
        b = function() private$..b$value),
    private = list(
        ..var = NA,
        ..bindistr = NA,
        ..geodistr = NA,
        ..podistr = NA,
        ..Ndistr = NA,
        ..expdistr = NA,
        ..Udistr = NA,
        ..pardistr = NA,
        ..powdistr = NA,
        ..variance = NA,
        ..mean = NA,
        ..mu = NA,
        ..expparameter = NA,
        ..unifa = NA,
        ..a = NA,
        ..unifb = NA,
        ..b = NA)
)

d3maximumlikelihoodResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d3maximumlikelihoodResults",
    inherit = jmvcore::Group,
    active = list(
        MLEbin = function() private$.items[["MLEbin"]],
        MLEgeo = function() private$.items[["MLEgeo"]],
        MLEpo = function() private$.items[["MLEpo"]],
        MLEnorm = function() private$.items[["MLEnorm"]],
        MLEexp = function() private$.items[["MLEexp"]],
        MLEunif = function() private$.items[["MLEunif"]],
        MLEpar = function() private$.items[["MLEpar"]],
        MLEpow = function() private$.items[["MLEpow"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Maximum Likelihood Estimation (D3/D5)")
            self$add(jmvcore::Table$new(
                options=options,
                name="MLEbin",
                title="Maximum-Likelihood-Estimator for Binomial distribution",
                visible="(bindistr && !is.null(var))",
                rows=1,
                columns=list(
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="MLE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="MLEgeo",
                title="Maximum-Likelihood-Estimator for Geometric distribution",
                visible="(geodistr && !is.null(var))",
                rows=1,
                columns=list(
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="MLE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="MLEpo",
                title="Maximum-Likelihood-Estimator for Poisson distribution",
                visible="(podistr && !is.null(var))",
                rows=1,
                columns=list(
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="MLE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="MLEnorm",
                title="Maximum-Likelihood-Estimator for Normal distribution",
                visible="(Ndistr && !is.null(var))",
                rows=1,
                columns=list(
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="MLE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="MLEexp",
                title="Maximum-Likelihood-Estimator for Exponential distribution",
                visible="(expdistr && !is.null(var))",
                rows=1,
                columns=list(
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="MLE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="MLEunif",
                title="Maximum-Likelihood-Estimator for Uniform distribution",
                visible="(Udistr && !is.null(var))",
                rows=1,
                columns=list(
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="MLE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="MLEpar",
                title="Maximum-Likelihood-Estimator for Pareto distribution",
                visible="(pardistr && !is.null(var))",
                rows=1,
                columns=list(
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="MLE", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="MLEpow",
                title="Maximum-Likelihood-Estimator for Power distribution",
                visible="(powdistr && !is.null(var))",
                rows=1,
                columns=list(
                    list(
                        `name`="par", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="MLE", 
                        `type`="number"))))}))

d3maximumlikelihoodBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d3maximumlikelihoodBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "d3maximumlikelihood",
                version = c(1,0,0),
                options = options,
                results = d3maximumlikelihoodResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Maximum Likelihood Estimation (D3/D5)
#'
#' 
#' @param data .
#' @param var .
#' @param bindistr .
#' @param geodistr .
#' @param podistr .
#' @param Ndistr .
#' @param expdistr .
#' @param Udistr .
#' @param pardistr .
#' @param powdistr .
#' @param variance .
#' @param mean .
#' @param mu .
#' @param expparameter .
#' @param unifa .
#' @param a .
#' @param unifb .
#' @param b .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$MLEbin} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MLEgeo} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MLEpo} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MLEnorm} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MLEexp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MLEunif} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MLEpar} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MLEpow} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$MLEbin$asDF}
#'
#' \code{as.data.frame(results$MLEbin)}
#'
#' @export
d3maximumlikelihood <- function(
    data,
    var,
    bindistr = FALSE,
    geodistr = FALSE,
    podistr = FALSE,
    Ndistr = FALSE,
    expdistr = FALSE,
    Udistr = FALSE,
    pardistr = FALSE,
    powdistr = FALSE,
    variance = FALSE,
    mean = FALSE,
    mu = 0,
    expparameter,
    unifa = FALSE,
    a = 0,
    unifb = FALSE,
    b = 1) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("d3maximumlikelihood requires jmvcore to be installed (restart may be required)")

    if ( ! missing(var)) var <- jmvcore::resolveQuo(jmvcore::enquo(var))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(var), var, NULL))


    options <- d3maximumlikelihoodOptions$new(
        var = var,
        bindistr = bindistr,
        geodistr = geodistr,
        podistr = podistr,
        Ndistr = Ndistr,
        expdistr = expdistr,
        Udistr = Udistr,
        pardistr = pardistr,
        powdistr = powdistr,
        variance = variance,
        mean = mean,
        mu = mu,
        expparameter = expparameter,
        unifa = unifa,
        a = a,
        unifb = unifb,
        b = b)

    analysis <- d3maximumlikelihoodClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

