
# This file is automatically generated, you probably don't want to edit this

d4confidenceintervalsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d4confidenceintervalsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varnorm = NULL,
            normalpha = 0.95,
            muunknownvar = FALSE,
            sidemuunknownvar = "twomuunknownvar",
            muknownvar = FALSE,
            sigmasq = 1,
            sidemuknownvar = "twomuknownvar",
            n = FALSE,
            L0 = 1,
            sigmaunknownmu = FALSE,
            sidesigmaunknownmu = "twosigmaunknownmu",
            sigmaknownmu = FALSE,
            mu = 0,
            sidesigmaknownmu = "twosigmaknownmu",
            varnormtwosample = NULL,
            split = NULL,
            normalphatwosample = 0.95,
            diff = FALSE,
            sidediff = "twodiff",
            varbinom = NULL,
            binalpha = 0.95,
            exact = FALSE,
            sidebinexact = "twobinexact",
            approx = FALSE,
            sidebinapprox = "twobinapprox",
            varexp = NULL,
            expalpha = 0.95,
            lambda = FALSE,
            sideexp = "twoexp",
            beta = FALSE,
            sidebetaexp = "twobetaexp", ...) {

            super$initialize(
                package="jamoviRWTH",
                name="d4confidenceintervals",
                requiresData=TRUE,
                ...)

            private$..varnorm <- jmvcore::OptionVariable$new(
                "varnorm",
                varnorm,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..normalpha <- jmvcore::OptionNumber$new(
                "normalpha",
                normalpha,
                default=0.95)
            private$..muunknownvar <- jmvcore::OptionBool$new(
                "muunknownvar",
                muunknownvar,
                default=FALSE)
            private$..sidemuunknownvar <- jmvcore::OptionList$new(
                "sidemuunknownvar",
                sidemuunknownvar,
                options=list(
                    "lowermuunknownvar",
                    "uppermuunknownvar",
                    "twomuunknownvar"),
                default="twomuunknownvar")
            private$..muknownvar <- jmvcore::OptionBool$new(
                "muknownvar",
                muknownvar,
                default=FALSE)
            private$..sigmasq <- jmvcore::OptionNumber$new(
                "sigmasq",
                sigmasq,
                default=1)
            private$..sidemuknownvar <- jmvcore::OptionList$new(
                "sidemuknownvar",
                sidemuknownvar,
                options=list(
                    "lowermuknownvar",
                    "uppermuknownvar",
                    "twomuknownvar"),
                default="twomuknownvar")
            private$..n <- jmvcore::OptionBool$new(
                "n",
                n,
                default=FALSE)
            private$..L0 <- jmvcore::OptionNumber$new(
                "L0",
                L0,
                default=1)
            private$..sigmaunknownmu <- jmvcore::OptionBool$new(
                "sigmaunknownmu",
                sigmaunknownmu,
                default=FALSE)
            private$..sidesigmaunknownmu <- jmvcore::OptionList$new(
                "sidesigmaunknownmu",
                sidesigmaunknownmu,
                options=list(
                    "lowersigmaunknownmu",
                    "uppersigmaunknownmu",
                    "twosigmaunknownmu"),
                default="twosigmaunknownmu")
            private$..sigmaknownmu <- jmvcore::OptionBool$new(
                "sigmaknownmu",
                sigmaknownmu,
                default=FALSE)
            private$..mu <- jmvcore::OptionNumber$new(
                "mu",
                mu,
                default=0)
            private$..sidesigmaknownmu <- jmvcore::OptionList$new(
                "sidesigmaknownmu",
                sidesigmaknownmu,
                options=list(
                    "lowersigmaknownmu",
                    "uppersigmaknownmu",
                    "twosigmaknownmu"),
                default="twosigmaknownmu")
            private$..varnormtwosample <- jmvcore::OptionVariable$new(
                "varnormtwosample",
                varnormtwosample,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..split <- jmvcore::OptionVariable$new(
                "split",
                split,
                permitted=list(
                    "factor"),
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..normalphatwosample <- jmvcore::OptionNumber$new(
                "normalphatwosample",
                normalphatwosample,
                default=0.95)
            private$..diff <- jmvcore::OptionBool$new(
                "diff",
                diff,
                default=FALSE)
            private$..sidediff <- jmvcore::OptionList$new(
                "sidediff",
                sidediff,
                options=list(
                    "lowerdiff",
                    "upperdiff",
                    "twodiff"),
                default="twodiff")
            private$..varbinom <- jmvcore::OptionVariable$new(
                "varbinom",
                varbinom,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..binalpha <- jmvcore::OptionNumber$new(
                "binalpha",
                binalpha,
                default=0.95)
            private$..exact <- jmvcore::OptionBool$new(
                "exact",
                exact,
                default=FALSE)
            private$..sidebinexact <- jmvcore::OptionList$new(
                "sidebinexact",
                sidebinexact,
                options=list(
                    "lowerbinexact",
                    "upperbinexact",
                    "twobinexact"),
                default="twobinexact")
            private$..approx <- jmvcore::OptionBool$new(
                "approx",
                approx,
                default=FALSE)
            private$..sidebinapprox <- jmvcore::OptionList$new(
                "sidebinapprox",
                sidebinapprox,
                options=list(
                    "lowerbinapprox",
                    "upperbinapprox",
                    "twobinapprox"),
                default="twobinapprox")
            private$..varexp <- jmvcore::OptionVariable$new(
                "varexp",
                varexp,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..expalpha <- jmvcore::OptionNumber$new(
                "expalpha",
                expalpha,
                default=0.95)
            private$..lambda <- jmvcore::OptionBool$new(
                "lambda",
                lambda,
                default=FALSE)
            private$..sideexp <- jmvcore::OptionList$new(
                "sideexp",
                sideexp,
                options=list(
                    "lowerexp",
                    "upperexp",
                    "twoexp"),
                default="twoexp")
            private$..beta <- jmvcore::OptionBool$new(
                "beta",
                beta,
                default=FALSE)
            private$..sidebetaexp <- jmvcore::OptionList$new(
                "sidebetaexp",
                sidebetaexp,
                options=list(
                    "lowerbetaexp",
                    "upperbetaexp",
                    "twobetaexp"),
                default="twobetaexp")

            self$.addOption(private$..varnorm)
            self$.addOption(private$..normalpha)
            self$.addOption(private$..muunknownvar)
            self$.addOption(private$..sidemuunknownvar)
            self$.addOption(private$..muknownvar)
            self$.addOption(private$..sigmasq)
            self$.addOption(private$..sidemuknownvar)
            self$.addOption(private$..n)
            self$.addOption(private$..L0)
            self$.addOption(private$..sigmaunknownmu)
            self$.addOption(private$..sidesigmaunknownmu)
            self$.addOption(private$..sigmaknownmu)
            self$.addOption(private$..mu)
            self$.addOption(private$..sidesigmaknownmu)
            self$.addOption(private$..varnormtwosample)
            self$.addOption(private$..split)
            self$.addOption(private$..normalphatwosample)
            self$.addOption(private$..diff)
            self$.addOption(private$..sidediff)
            self$.addOption(private$..varbinom)
            self$.addOption(private$..binalpha)
            self$.addOption(private$..exact)
            self$.addOption(private$..sidebinexact)
            self$.addOption(private$..approx)
            self$.addOption(private$..sidebinapprox)
            self$.addOption(private$..varexp)
            self$.addOption(private$..expalpha)
            self$.addOption(private$..lambda)
            self$.addOption(private$..sideexp)
            self$.addOption(private$..beta)
            self$.addOption(private$..sidebetaexp)
        }),
    active = list(
        varnorm = function() private$..varnorm$value,
        normalpha = function() private$..normalpha$value,
        muunknownvar = function() private$..muunknownvar$value,
        sidemuunknownvar = function() private$..sidemuunknownvar$value,
        muknownvar = function() private$..muknownvar$value,
        sigmasq = function() private$..sigmasq$value,
        sidemuknownvar = function() private$..sidemuknownvar$value,
        n = function() private$..n$value,
        L0 = function() private$..L0$value,
        sigmaunknownmu = function() private$..sigmaunknownmu$value,
        sidesigmaunknownmu = function() private$..sidesigmaunknownmu$value,
        sigmaknownmu = function() private$..sigmaknownmu$value,
        mu = function() private$..mu$value,
        sidesigmaknownmu = function() private$..sidesigmaknownmu$value,
        varnormtwosample = function() private$..varnormtwosample$value,
        split = function() private$..split$value,
        normalphatwosample = function() private$..normalphatwosample$value,
        diff = function() private$..diff$value,
        sidediff = function() private$..sidediff$value,
        varbinom = function() private$..varbinom$value,
        binalpha = function() private$..binalpha$value,
        exact = function() private$..exact$value,
        sidebinexact = function() private$..sidebinexact$value,
        approx = function() private$..approx$value,
        sidebinapprox = function() private$..sidebinapprox$value,
        varexp = function() private$..varexp$value,
        expalpha = function() private$..expalpha$value,
        lambda = function() private$..lambda$value,
        sideexp = function() private$..sideexp$value,
        beta = function() private$..beta$value,
        sidebetaexp = function() private$..sidebetaexp$value),
    private = list(
        ..varnorm = NA,
        ..normalpha = NA,
        ..muunknownvar = NA,
        ..sidemuunknownvar = NA,
        ..muknownvar = NA,
        ..sigmasq = NA,
        ..sidemuknownvar = NA,
        ..n = NA,
        ..L0 = NA,
        ..sigmaunknownmu = NA,
        ..sidesigmaunknownmu = NA,
        ..sigmaknownmu = NA,
        ..mu = NA,
        ..sidesigmaknownmu = NA,
        ..varnormtwosample = NA,
        ..split = NA,
        ..normalphatwosample = NA,
        ..diff = NA,
        ..sidediff = NA,
        ..varbinom = NA,
        ..binalpha = NA,
        ..exact = NA,
        ..sidebinexact = NA,
        ..approx = NA,
        ..sidebinapprox = NA,
        ..varexp = NA,
        ..expalpha = NA,
        ..lambda = NA,
        ..sideexp = NA,
        ..beta = NA,
        ..sidebetaexp = NA)
)

d4confidenceintervalsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d4confidenceintervalsResults",
    inherit = jmvcore::Group,
    active = list(
        CIexp = function() private$.items[["CIexp"]],
        CIbin = function() private$.items[["CIbin"]],
        CInorm = function() private$.items[["CInorm"]],
        CInormtwosample = function() private$.items[["CInormtwosample"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Confidence Intervals (D4/D5)")
            self$add(jmvcore::Table$new(
                options=options,
                name="CIexp",
                title="Confidence interval for exponential distribution",
                visible="(lambda && !is.null(varexp) || beta && !is.null(varexp))",
                columns=list(
                    list(
                        `name`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="Level", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="CIbin",
                title="Confidence interval for binomial distribution",
                visible="(exact && !is.null(varbinom) || approx && !is.null(varbinom))",
                columns=list(
                    list(
                        `name`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="Level", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"),
                    list(
                        `name`="Type", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="CInorm",
                title="Confidence intervals for normal distribution",
                visible="(muknownvar && !is.null(varnorm) || muunknownvar && !is.null(varnorm) || sigmaknownmu && !is.null(varnorm) || sigmaunknownmu && !is.null(varnorm))",
                columns=list(
                    list(
                        `name`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="Level", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"),
                    list(
                        `name`="n", 
                        `title`="n \u2265", 
                        `type`="number", 
                        `visible`="(n && muknownvar)"),
                    list(
                        `name`="Type", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="CInormtwosample",
                title="Confidence interval for two independent samples from a normal distribution",
                visible="(diff && !is.null(varnormtwosample) && !is.null(split))",
                columns=list(
                    list(
                        `name`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="Level", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `type`="number"),
                    list(
                        `name`="Type", 
                        `type`="text"))))}))

d4confidenceintervalsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d4confidenceintervalsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "d4confidenceintervals",
                version = c(1,0,0),
                options = options,
                results = d4confidenceintervalsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Confidence Intervals (D4/D5)
#'
#' 
#' @param data .
#' @param varnorm .
#' @param normalpha .
#' @param muunknownvar .
#' @param sidemuunknownvar .
#' @param muknownvar .
#' @param sigmasq .
#' @param sidemuknownvar .
#' @param n .
#' @param L0 .
#' @param sigmaunknownmu .
#' @param sidesigmaunknownmu .
#' @param sigmaknownmu .
#' @param mu .
#' @param sidesigmaknownmu .
#' @param varnormtwosample .
#' @param split .
#' @param normalphatwosample .
#' @param diff .
#' @param sidediff .
#' @param varbinom .
#' @param binalpha .
#' @param exact .
#' @param sidebinexact .
#' @param approx .
#' @param sidebinapprox .
#' @param varexp .
#' @param expalpha .
#' @param lambda .
#' @param sideexp .
#' @param beta .
#' @param sidebetaexp .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$CIexp} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$CIbin} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$CInorm} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$CInormtwosample} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$CIexp$asDF}
#'
#' \code{as.data.frame(results$CIexp)}
#'
#' @export
d4confidenceintervals <- function(
    data,
    varnorm,
    normalpha = 0.95,
    muunknownvar = FALSE,
    sidemuunknownvar = "twomuunknownvar",
    muknownvar = FALSE,
    sigmasq = 1,
    sidemuknownvar = "twomuknownvar",
    n = FALSE,
    L0 = 1,
    sigmaunknownmu = FALSE,
    sidesigmaunknownmu = "twosigmaunknownmu",
    sigmaknownmu = FALSE,
    mu = 0,
    sidesigmaknownmu = "twosigmaknownmu",
    varnormtwosample,
    split,
    normalphatwosample = 0.95,
    diff = FALSE,
    sidediff = "twodiff",
    varbinom,
    binalpha = 0.95,
    exact = FALSE,
    sidebinexact = "twobinexact",
    approx = FALSE,
    sidebinapprox = "twobinapprox",
    varexp,
    expalpha = 0.95,
    lambda = FALSE,
    sideexp = "twoexp",
    beta = FALSE,
    sidebetaexp = "twobetaexp") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("d4confidenceintervals requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varnorm)) varnorm <- jmvcore::resolveQuo(jmvcore::enquo(varnorm))
    if ( ! missing(varnormtwosample)) varnormtwosample <- jmvcore::resolveQuo(jmvcore::enquo(varnormtwosample))
    if ( ! missing(split)) split <- jmvcore::resolveQuo(jmvcore::enquo(split))
    if ( ! missing(varbinom)) varbinom <- jmvcore::resolveQuo(jmvcore::enquo(varbinom))
    if ( ! missing(varexp)) varexp <- jmvcore::resolveQuo(jmvcore::enquo(varexp))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varnorm), varnorm, NULL),
            `if`( ! missing(varnormtwosample), varnormtwosample, NULL),
            `if`( ! missing(split), split, NULL),
            `if`( ! missing(varbinom), varbinom, NULL),
            `if`( ! missing(varexp), varexp, NULL))

    for (v in split) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- d4confidenceintervalsOptions$new(
        varnorm = varnorm,
        normalpha = normalpha,
        muunknownvar = muunknownvar,
        sidemuunknownvar = sidemuunknownvar,
        muknownvar = muknownvar,
        sigmasq = sigmasq,
        sidemuknownvar = sidemuknownvar,
        n = n,
        L0 = L0,
        sigmaunknownmu = sigmaunknownmu,
        sidesigmaunknownmu = sidesigmaunknownmu,
        sigmaknownmu = sigmaknownmu,
        mu = mu,
        sidesigmaknownmu = sidesigmaknownmu,
        varnormtwosample = varnormtwosample,
        split = split,
        normalphatwosample = normalphatwosample,
        diff = diff,
        sidediff = sidediff,
        varbinom = varbinom,
        binalpha = binalpha,
        exact = exact,
        sidebinexact = sidebinexact,
        approx = approx,
        sidebinapprox = sidebinapprox,
        varexp = varexp,
        expalpha = expalpha,
        lambda = lambda,
        sideexp = sideexp,
        beta = beta,
        sidebetaexp = sidebetaexp)

    analysis <- d4confidenceintervalsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

