
# This file is automatically generated, you probably don't want to edit this

d6testsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d6testsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varnormalones = NULL,
            normalphaones = 0.05,
            ztest = FALSE,
            ztestvalue = 1,
            ztestsigma = 0.1,
            ztestside = "twoztest",
            ztestpower = FALSE,
            ztestpowervalue = 1,
            ztesttypeIerror = FALSE,
            ztesttypeIerrorvalue = 1,
            ztesttypeIIerror = FALSE,
            ztesttypeIIerrorvalue = 1,
            ztestexpdesign = FALSE,
            ztestexpdesignbeta = 0.5,
            ztestexpdesigndelta = 1,
            ttest = FALSE,
            ttestvalue = 1,
            ttestside = "twottest",
            chitestknownmu = FALSE,
            chitestvalueknownmu = 1,
            chitestmu = 2,
            chitestsideknownmu = "twochitestknownmu",
            chitest = FALSE,
            chitestvalue = 1,
            chitestside = "twochitest",
            varnormalpaired1 = NULL,
            varnormalpaired2 = NULL,
            normalphapaired = 0.05,
            ztestpaired = FALSE,
            ztestpairedvalue = 1,
            ztestpairedsigma1 = 1,
            ztestpairedsigma2 = 1,
            ztestpairedrho = 0.1,
            ztestpairedside = "twoztestpaired",
            ttestpaired = FALSE,
            ttestpairedvalue = 1,
            ttestpairedside = "twottestpaired",
            indeptestpaired = FALSE,
            indeptestpairedside = "twoindeptestpaired",
            varnormalindep = NULL,
            splitnormal = NULL,
            normalphaindep = 0.05,
            ftest = FALSE,
            ftestside = "twoftest",
            ztestindep = FALSE,
            ztestindepsigma = 0.1,
            ztestindepside = "twoztestindep",
            ttestindep = FALSE,
            ttestindepside = "twottestindep",
            varbinones = NULL,
            binalphaones = 0.05,
            exactbintest = FALSE,
            exactbintestvalue = 0.5,
            exactbintestside = "twoexactbintest",
            exactbintestpower = FALSE,
            exactbintestpowervalue = 0.5,
            exactbintesttypeIerror = FALSE,
            exactbintesttypeIerrorvalue = 0.1,
            exactbintesttypeIIerror = FALSE,
            exactbintesttypeIIerrorvalue = 0.1,
            approxbintest = FALSE,
            approxbintestvalue = 0.5,
            approxbintestside = "twoapproxbintest",
            varbintwos = NULL,
            splitbin = NULL,
            binalphaindep = 0.05,
            twosamplesbintest = FALSE,
            twosamplesbintestside = "twotwosamplesbintest",
            varnonparamones = NULL,
            nonparamalphaones = 0.05,
            signtest = FALSE,
            signtestvalue = 0,
            signtestside = "twosigntest",
            varnonparamtwos = NULL,
            splitnonparam = NULL,
            nonparamalphatwos = 0.05,
            utest = FALSE,
            utestside = "twoutest",
            nominal1 = NULL,
            nominal2 = NULL,
            counts = NULL,
            contabs = FALSE,
            conttest = FALSE,
            conttestalpha = 0.05, ...) {

            super$initialize(
                package="jamoviRWTH",
                name="d6tests",
                requiresData=TRUE,
                ...)

            private$..varnormalones <- jmvcore::OptionVariable$new(
                "varnormalones",
                varnormalones,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..normalphaones <- jmvcore::OptionNumber$new(
                "normalphaones",
                normalphaones,
                default=0.05)
            private$..ztest <- jmvcore::OptionBool$new(
                "ztest",
                ztest,
                default=FALSE)
            private$..ztestvalue <- jmvcore::OptionNumber$new(
                "ztestvalue",
                ztestvalue,
                default=1)
            private$..ztestsigma <- jmvcore::OptionNumber$new(
                "ztestsigma",
                ztestsigma,
                default=0.1)
            private$..ztestside <- jmvcore::OptionList$new(
                "ztestside",
                ztestside,
                options=list(
                    "twoztest",
                    "lowerztest",
                    "upperztest"),
                default="twoztest")
            private$..ztestpower <- jmvcore::OptionBool$new(
                "ztestpower",
                ztestpower,
                default=FALSE)
            private$..ztestpowervalue <- jmvcore::OptionNumber$new(
                "ztestpowervalue",
                ztestpowervalue,
                default=1)
            private$..ztesttypeIerror <- jmvcore::OptionBool$new(
                "ztesttypeIerror",
                ztesttypeIerror,
                default=FALSE)
            private$..ztesttypeIerrorvalue <- jmvcore::OptionNumber$new(
                "ztesttypeIerrorvalue",
                ztesttypeIerrorvalue,
                default=1)
            private$..ztesttypeIIerror <- jmvcore::OptionBool$new(
                "ztesttypeIIerror",
                ztesttypeIIerror,
                default=FALSE)
            private$..ztesttypeIIerrorvalue <- jmvcore::OptionNumber$new(
                "ztesttypeIIerrorvalue",
                ztesttypeIIerrorvalue,
                default=1)
            private$..ztestexpdesign <- jmvcore::OptionBool$new(
                "ztestexpdesign",
                ztestexpdesign,
                default=FALSE)
            private$..ztestexpdesignbeta <- jmvcore::OptionNumber$new(
                "ztestexpdesignbeta",
                ztestexpdesignbeta,
                default=0.5)
            private$..ztestexpdesigndelta <- jmvcore::OptionNumber$new(
                "ztestexpdesigndelta",
                ztestexpdesigndelta,
                default=1)
            private$..ttest <- jmvcore::OptionBool$new(
                "ttest",
                ttest,
                default=FALSE)
            private$..ttestvalue <- jmvcore::OptionNumber$new(
                "ttestvalue",
                ttestvalue,
                default=1)
            private$..ttestside <- jmvcore::OptionList$new(
                "ttestside",
                ttestside,
                options=list(
                    "twottest",
                    "lowerttest",
                    "upperttest"),
                default="twottest")
            private$..chitestknownmu <- jmvcore::OptionBool$new(
                "chitestknownmu",
                chitestknownmu,
                default=FALSE)
            private$..chitestvalueknownmu <- jmvcore::OptionNumber$new(
                "chitestvalueknownmu",
                chitestvalueknownmu,
                default=1)
            private$..chitestmu <- jmvcore::OptionNumber$new(
                "chitestmu",
                chitestmu,
                default=2)
            private$..chitestsideknownmu <- jmvcore::OptionList$new(
                "chitestsideknownmu",
                chitestsideknownmu,
                options=list(
                    "twochitestknownmu",
                    "lowerchitestknownmu",
                    "upperchitestknownmu"),
                default="twochitestknownmu")
            private$..chitest <- jmvcore::OptionBool$new(
                "chitest",
                chitest,
                default=FALSE)
            private$..chitestvalue <- jmvcore::OptionNumber$new(
                "chitestvalue",
                chitestvalue,
                default=1)
            private$..chitestside <- jmvcore::OptionList$new(
                "chitestside",
                chitestside,
                options=list(
                    "twochitest",
                    "lowerchitest",
                    "upperchitest"),
                default="twochitest")
            private$..varnormalpaired1 <- jmvcore::OptionVariable$new(
                "varnormalpaired1",
                varnormalpaired1,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..varnormalpaired2 <- jmvcore::OptionVariable$new(
                "varnormalpaired2",
                varnormalpaired2,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..normalphapaired <- jmvcore::OptionNumber$new(
                "normalphapaired",
                normalphapaired,
                default=0.05)
            private$..ztestpaired <- jmvcore::OptionBool$new(
                "ztestpaired",
                ztestpaired,
                default=FALSE)
            private$..ztestpairedvalue <- jmvcore::OptionNumber$new(
                "ztestpairedvalue",
                ztestpairedvalue,
                default=1)
            private$..ztestpairedsigma1 <- jmvcore::OptionNumber$new(
                "ztestpairedsigma1",
                ztestpairedsigma1,
                default=1)
            private$..ztestpairedsigma2 <- jmvcore::OptionNumber$new(
                "ztestpairedsigma2",
                ztestpairedsigma2,
                default=1)
            private$..ztestpairedrho <- jmvcore::OptionNumber$new(
                "ztestpairedrho",
                ztestpairedrho,
                default=0.1)
            private$..ztestpairedside <- jmvcore::OptionList$new(
                "ztestpairedside",
                ztestpairedside,
                options=list(
                    "twoztestpaired",
                    "lowerztestpaired",
                    "upperztestpaired"),
                default="twoztestpaired")
            private$..ttestpaired <- jmvcore::OptionBool$new(
                "ttestpaired",
                ttestpaired,
                default=FALSE)
            private$..ttestpairedvalue <- jmvcore::OptionNumber$new(
                "ttestpairedvalue",
                ttestpairedvalue,
                default=1)
            private$..ttestpairedside <- jmvcore::OptionList$new(
                "ttestpairedside",
                ttestpairedside,
                options=list(
                    "twottestpaired",
                    "lowerttestpaired",
                    "upperttestpaired"),
                default="twottestpaired")
            private$..indeptestpaired <- jmvcore::OptionBool$new(
                "indeptestpaired",
                indeptestpaired,
                default=FALSE)
            private$..indeptestpairedside <- jmvcore::OptionList$new(
                "indeptestpairedside",
                indeptestpairedside,
                options=list(
                    "twoindeptestpaired",
                    "lowerindeptestpaired",
                    "upperindeptestpaired"),
                default="twoindeptestpaired")
            private$..varnormalindep <- jmvcore::OptionVariable$new(
                "varnormalindep",
                varnormalindep,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..splitnormal <- jmvcore::OptionVariable$new(
                "splitnormal",
                splitnormal,
                permitted=list(
                    "factor"),
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..normalphaindep <- jmvcore::OptionNumber$new(
                "normalphaindep",
                normalphaindep,
                default=0.05)
            private$..ftest <- jmvcore::OptionBool$new(
                "ftest",
                ftest,
                default=FALSE)
            private$..ftestside <- jmvcore::OptionList$new(
                "ftestside",
                ftestside,
                options=list(
                    "twoftest",
                    "lowerftest",
                    "upperftest"),
                default="twoftest")
            private$..ztestindep <- jmvcore::OptionBool$new(
                "ztestindep",
                ztestindep,
                default=FALSE)
            private$..ztestindepsigma <- jmvcore::OptionNumber$new(
                "ztestindepsigma",
                ztestindepsigma,
                default=0.1)
            private$..ztestindepside <- jmvcore::OptionList$new(
                "ztestindepside",
                ztestindepside,
                options=list(
                    "twoztestindep",
                    "lowerztestindep",
                    "upperztestindep"),
                default="twoztestindep")
            private$..ttestindep <- jmvcore::OptionBool$new(
                "ttestindep",
                ttestindep,
                default=FALSE)
            private$..ttestindepside <- jmvcore::OptionList$new(
                "ttestindepside",
                ttestindepside,
                options=list(
                    "twottestindep",
                    "lowerttestindep",
                    "upperttestindep"),
                default="twottestindep")
            private$..varbinones <- jmvcore::OptionVariable$new(
                "varbinones",
                varbinones,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..binalphaones <- jmvcore::OptionNumber$new(
                "binalphaones",
                binalphaones,
                default=0.05)
            private$..exactbintest <- jmvcore::OptionBool$new(
                "exactbintest",
                exactbintest,
                default=FALSE)
            private$..exactbintestvalue <- jmvcore::OptionNumber$new(
                "exactbintestvalue",
                exactbintestvalue,
                default=0.5)
            private$..exactbintestside <- jmvcore::OptionList$new(
                "exactbintestside",
                exactbintestside,
                options=list(
                    "twoexactbintest",
                    "lowerexactbintest",
                    "upperexactbintest"),
                default="twoexactbintest")
            private$..exactbintestpower <- jmvcore::OptionBool$new(
                "exactbintestpower",
                exactbintestpower,
                default=FALSE)
            private$..exactbintestpowervalue <- jmvcore::OptionNumber$new(
                "exactbintestpowervalue",
                exactbintestpowervalue,
                default=0.5)
            private$..exactbintesttypeIerror <- jmvcore::OptionBool$new(
                "exactbintesttypeIerror",
                exactbintesttypeIerror,
                default=FALSE)
            private$..exactbintesttypeIerrorvalue <- jmvcore::OptionNumber$new(
                "exactbintesttypeIerrorvalue",
                exactbintesttypeIerrorvalue,
                default=0.1)
            private$..exactbintesttypeIIerror <- jmvcore::OptionBool$new(
                "exactbintesttypeIIerror",
                exactbintesttypeIIerror,
                default=FALSE)
            private$..exactbintesttypeIIerrorvalue <- jmvcore::OptionNumber$new(
                "exactbintesttypeIIerrorvalue",
                exactbintesttypeIIerrorvalue,
                default=0.1)
            private$..approxbintest <- jmvcore::OptionBool$new(
                "approxbintest",
                approxbintest,
                default=FALSE)
            private$..approxbintestvalue <- jmvcore::OptionNumber$new(
                "approxbintestvalue",
                approxbintestvalue,
                default=0.5)
            private$..approxbintestside <- jmvcore::OptionList$new(
                "approxbintestside",
                approxbintestside,
                options=list(
                    "twoapproxbintest",
                    "lowerapproxbintest",
                    "upperapproxbintest"),
                default="twoapproxbintest")
            private$..varbintwos <- jmvcore::OptionVariable$new(
                "varbintwos",
                varbintwos,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..splitbin <- jmvcore::OptionVariable$new(
                "splitbin",
                splitbin,
                permitted=list(
                    "factor"),
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..binalphaindep <- jmvcore::OptionNumber$new(
                "binalphaindep",
                binalphaindep,
                default=0.05)
            private$..twosamplesbintest <- jmvcore::OptionBool$new(
                "twosamplesbintest",
                twosamplesbintest,
                default=FALSE)
            private$..twosamplesbintestside <- jmvcore::OptionList$new(
                "twosamplesbintestside",
                twosamplesbintestside,
                options=list(
                    "twotwosamplesbintest",
                    "lowertwosamplesbintest",
                    "uppertwosamplesbintest"),
                default="twotwosamplesbintest")
            private$..varnonparamones <- jmvcore::OptionVariable$new(
                "varnonparamones",
                varnonparamones,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..nonparamalphaones <- jmvcore::OptionNumber$new(
                "nonparamalphaones",
                nonparamalphaones,
                default=0.05)
            private$..signtest <- jmvcore::OptionBool$new(
                "signtest",
                signtest,
                default=FALSE)
            private$..signtestvalue <- jmvcore::OptionNumber$new(
                "signtestvalue",
                signtestvalue,
                default=0)
            private$..signtestside <- jmvcore::OptionList$new(
                "signtestside",
                signtestside,
                options=list(
                    "twosigntest",
                    "lowersigntest",
                    "uppersigntest"),
                default="twosigntest")
            private$..varnonparamtwos <- jmvcore::OptionVariable$new(
                "varnonparamtwos",
                varnonparamtwos,
                permitted=list(
                    "numeric"),
                suggested=list(
                    "continuous"))
            private$..splitnonparam <- jmvcore::OptionVariable$new(
                "splitnonparam",
                splitnonparam,
                permitted=list(
                    "factor"),
                suggested=list(
                    "nominal",
                    "ordinal"))
            private$..nonparamalphatwos <- jmvcore::OptionNumber$new(
                "nonparamalphatwos",
                nonparamalphatwos,
                default=0.05)
            private$..utest <- jmvcore::OptionBool$new(
                "utest",
                utest,
                default=FALSE)
            private$..utestside <- jmvcore::OptionList$new(
                "utestside",
                utestside,
                options=list(
                    "twoutest",
                    "lowerutest",
                    "upperutest"),
                default="twoutest")
            private$..nominal1 <- jmvcore::OptionVariable$new(
                "nominal1",
                nominal1,
                permitted=list(
                    "factor",
                    "id"),
                suggested=list(
                    "nominal"))
            private$..nominal2 <- jmvcore::OptionVariable$new(
                "nominal2",
                nominal2,
                permitted=list(
                    "factor",
                    "id"),
                suggested=list(
                    "nominal"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..contabs <- jmvcore::OptionBool$new(
                "contabs",
                contabs,
                default=FALSE)
            private$..conttest <- jmvcore::OptionBool$new(
                "conttest",
                conttest,
                default=FALSE)
            private$..conttestalpha <- jmvcore::OptionNumber$new(
                "conttestalpha",
                conttestalpha,
                default=0.05)

            self$.addOption(private$..varnormalones)
            self$.addOption(private$..normalphaones)
            self$.addOption(private$..ztest)
            self$.addOption(private$..ztestvalue)
            self$.addOption(private$..ztestsigma)
            self$.addOption(private$..ztestside)
            self$.addOption(private$..ztestpower)
            self$.addOption(private$..ztestpowervalue)
            self$.addOption(private$..ztesttypeIerror)
            self$.addOption(private$..ztesttypeIerrorvalue)
            self$.addOption(private$..ztesttypeIIerror)
            self$.addOption(private$..ztesttypeIIerrorvalue)
            self$.addOption(private$..ztestexpdesign)
            self$.addOption(private$..ztestexpdesignbeta)
            self$.addOption(private$..ztestexpdesigndelta)
            self$.addOption(private$..ttest)
            self$.addOption(private$..ttestvalue)
            self$.addOption(private$..ttestside)
            self$.addOption(private$..chitestknownmu)
            self$.addOption(private$..chitestvalueknownmu)
            self$.addOption(private$..chitestmu)
            self$.addOption(private$..chitestsideknownmu)
            self$.addOption(private$..chitest)
            self$.addOption(private$..chitestvalue)
            self$.addOption(private$..chitestside)
            self$.addOption(private$..varnormalpaired1)
            self$.addOption(private$..varnormalpaired2)
            self$.addOption(private$..normalphapaired)
            self$.addOption(private$..ztestpaired)
            self$.addOption(private$..ztestpairedvalue)
            self$.addOption(private$..ztestpairedsigma1)
            self$.addOption(private$..ztestpairedsigma2)
            self$.addOption(private$..ztestpairedrho)
            self$.addOption(private$..ztestpairedside)
            self$.addOption(private$..ttestpaired)
            self$.addOption(private$..ttestpairedvalue)
            self$.addOption(private$..ttestpairedside)
            self$.addOption(private$..indeptestpaired)
            self$.addOption(private$..indeptestpairedside)
            self$.addOption(private$..varnormalindep)
            self$.addOption(private$..splitnormal)
            self$.addOption(private$..normalphaindep)
            self$.addOption(private$..ftest)
            self$.addOption(private$..ftestside)
            self$.addOption(private$..ztestindep)
            self$.addOption(private$..ztestindepsigma)
            self$.addOption(private$..ztestindepside)
            self$.addOption(private$..ttestindep)
            self$.addOption(private$..ttestindepside)
            self$.addOption(private$..varbinones)
            self$.addOption(private$..binalphaones)
            self$.addOption(private$..exactbintest)
            self$.addOption(private$..exactbintestvalue)
            self$.addOption(private$..exactbintestside)
            self$.addOption(private$..exactbintestpower)
            self$.addOption(private$..exactbintestpowervalue)
            self$.addOption(private$..exactbintesttypeIerror)
            self$.addOption(private$..exactbintesttypeIerrorvalue)
            self$.addOption(private$..exactbintesttypeIIerror)
            self$.addOption(private$..exactbintesttypeIIerrorvalue)
            self$.addOption(private$..approxbintest)
            self$.addOption(private$..approxbintestvalue)
            self$.addOption(private$..approxbintestside)
            self$.addOption(private$..varbintwos)
            self$.addOption(private$..splitbin)
            self$.addOption(private$..binalphaindep)
            self$.addOption(private$..twosamplesbintest)
            self$.addOption(private$..twosamplesbintestside)
            self$.addOption(private$..varnonparamones)
            self$.addOption(private$..nonparamalphaones)
            self$.addOption(private$..signtest)
            self$.addOption(private$..signtestvalue)
            self$.addOption(private$..signtestside)
            self$.addOption(private$..varnonparamtwos)
            self$.addOption(private$..splitnonparam)
            self$.addOption(private$..nonparamalphatwos)
            self$.addOption(private$..utest)
            self$.addOption(private$..utestside)
            self$.addOption(private$..nominal1)
            self$.addOption(private$..nominal2)
            self$.addOption(private$..counts)
            self$.addOption(private$..contabs)
            self$.addOption(private$..conttest)
            self$.addOption(private$..conttestalpha)
        }),
    active = list(
        varnormalones = function() private$..varnormalones$value,
        normalphaones = function() private$..normalphaones$value,
        ztest = function() private$..ztest$value,
        ztestvalue = function() private$..ztestvalue$value,
        ztestsigma = function() private$..ztestsigma$value,
        ztestside = function() private$..ztestside$value,
        ztestpower = function() private$..ztestpower$value,
        ztestpowervalue = function() private$..ztestpowervalue$value,
        ztesttypeIerror = function() private$..ztesttypeIerror$value,
        ztesttypeIerrorvalue = function() private$..ztesttypeIerrorvalue$value,
        ztesttypeIIerror = function() private$..ztesttypeIIerror$value,
        ztesttypeIIerrorvalue = function() private$..ztesttypeIIerrorvalue$value,
        ztestexpdesign = function() private$..ztestexpdesign$value,
        ztestexpdesignbeta = function() private$..ztestexpdesignbeta$value,
        ztestexpdesigndelta = function() private$..ztestexpdesigndelta$value,
        ttest = function() private$..ttest$value,
        ttestvalue = function() private$..ttestvalue$value,
        ttestside = function() private$..ttestside$value,
        chitestknownmu = function() private$..chitestknownmu$value,
        chitestvalueknownmu = function() private$..chitestvalueknownmu$value,
        chitestmu = function() private$..chitestmu$value,
        chitestsideknownmu = function() private$..chitestsideknownmu$value,
        chitest = function() private$..chitest$value,
        chitestvalue = function() private$..chitestvalue$value,
        chitestside = function() private$..chitestside$value,
        varnormalpaired1 = function() private$..varnormalpaired1$value,
        varnormalpaired2 = function() private$..varnormalpaired2$value,
        normalphapaired = function() private$..normalphapaired$value,
        ztestpaired = function() private$..ztestpaired$value,
        ztestpairedvalue = function() private$..ztestpairedvalue$value,
        ztestpairedsigma1 = function() private$..ztestpairedsigma1$value,
        ztestpairedsigma2 = function() private$..ztestpairedsigma2$value,
        ztestpairedrho = function() private$..ztestpairedrho$value,
        ztestpairedside = function() private$..ztestpairedside$value,
        ttestpaired = function() private$..ttestpaired$value,
        ttestpairedvalue = function() private$..ttestpairedvalue$value,
        ttestpairedside = function() private$..ttestpairedside$value,
        indeptestpaired = function() private$..indeptestpaired$value,
        indeptestpairedside = function() private$..indeptestpairedside$value,
        varnormalindep = function() private$..varnormalindep$value,
        splitnormal = function() private$..splitnormal$value,
        normalphaindep = function() private$..normalphaindep$value,
        ftest = function() private$..ftest$value,
        ftestside = function() private$..ftestside$value,
        ztestindep = function() private$..ztestindep$value,
        ztestindepsigma = function() private$..ztestindepsigma$value,
        ztestindepside = function() private$..ztestindepside$value,
        ttestindep = function() private$..ttestindep$value,
        ttestindepside = function() private$..ttestindepside$value,
        varbinones = function() private$..varbinones$value,
        binalphaones = function() private$..binalphaones$value,
        exactbintest = function() private$..exactbintest$value,
        exactbintestvalue = function() private$..exactbintestvalue$value,
        exactbintestside = function() private$..exactbintestside$value,
        exactbintestpower = function() private$..exactbintestpower$value,
        exactbintestpowervalue = function() private$..exactbintestpowervalue$value,
        exactbintesttypeIerror = function() private$..exactbintesttypeIerror$value,
        exactbintesttypeIerrorvalue = function() private$..exactbintesttypeIerrorvalue$value,
        exactbintesttypeIIerror = function() private$..exactbintesttypeIIerror$value,
        exactbintesttypeIIerrorvalue = function() private$..exactbintesttypeIIerrorvalue$value,
        approxbintest = function() private$..approxbintest$value,
        approxbintestvalue = function() private$..approxbintestvalue$value,
        approxbintestside = function() private$..approxbintestside$value,
        varbintwos = function() private$..varbintwos$value,
        splitbin = function() private$..splitbin$value,
        binalphaindep = function() private$..binalphaindep$value,
        twosamplesbintest = function() private$..twosamplesbintest$value,
        twosamplesbintestside = function() private$..twosamplesbintestside$value,
        varnonparamones = function() private$..varnonparamones$value,
        nonparamalphaones = function() private$..nonparamalphaones$value,
        signtest = function() private$..signtest$value,
        signtestvalue = function() private$..signtestvalue$value,
        signtestside = function() private$..signtestside$value,
        varnonparamtwos = function() private$..varnonparamtwos$value,
        splitnonparam = function() private$..splitnonparam$value,
        nonparamalphatwos = function() private$..nonparamalphatwos$value,
        utest = function() private$..utest$value,
        utestside = function() private$..utestside$value,
        nominal1 = function() private$..nominal1$value,
        nominal2 = function() private$..nominal2$value,
        counts = function() private$..counts$value,
        contabs = function() private$..contabs$value,
        conttest = function() private$..conttest$value,
        conttestalpha = function() private$..conttestalpha$value),
    private = list(
        ..varnormalones = NA,
        ..normalphaones = NA,
        ..ztest = NA,
        ..ztestvalue = NA,
        ..ztestsigma = NA,
        ..ztestside = NA,
        ..ztestpower = NA,
        ..ztestpowervalue = NA,
        ..ztesttypeIerror = NA,
        ..ztesttypeIerrorvalue = NA,
        ..ztesttypeIIerror = NA,
        ..ztesttypeIIerrorvalue = NA,
        ..ztestexpdesign = NA,
        ..ztestexpdesignbeta = NA,
        ..ztestexpdesigndelta = NA,
        ..ttest = NA,
        ..ttestvalue = NA,
        ..ttestside = NA,
        ..chitestknownmu = NA,
        ..chitestvalueknownmu = NA,
        ..chitestmu = NA,
        ..chitestsideknownmu = NA,
        ..chitest = NA,
        ..chitestvalue = NA,
        ..chitestside = NA,
        ..varnormalpaired1 = NA,
        ..varnormalpaired2 = NA,
        ..normalphapaired = NA,
        ..ztestpaired = NA,
        ..ztestpairedvalue = NA,
        ..ztestpairedsigma1 = NA,
        ..ztestpairedsigma2 = NA,
        ..ztestpairedrho = NA,
        ..ztestpairedside = NA,
        ..ttestpaired = NA,
        ..ttestpairedvalue = NA,
        ..ttestpairedside = NA,
        ..indeptestpaired = NA,
        ..indeptestpairedside = NA,
        ..varnormalindep = NA,
        ..splitnormal = NA,
        ..normalphaindep = NA,
        ..ftest = NA,
        ..ftestside = NA,
        ..ztestindep = NA,
        ..ztestindepsigma = NA,
        ..ztestindepside = NA,
        ..ttestindep = NA,
        ..ttestindepside = NA,
        ..varbinones = NA,
        ..binalphaones = NA,
        ..exactbintest = NA,
        ..exactbintestvalue = NA,
        ..exactbintestside = NA,
        ..exactbintestpower = NA,
        ..exactbintestpowervalue = NA,
        ..exactbintesttypeIerror = NA,
        ..exactbintesttypeIerrorvalue = NA,
        ..exactbintesttypeIIerror = NA,
        ..exactbintesttypeIIerrorvalue = NA,
        ..approxbintest = NA,
        ..approxbintestvalue = NA,
        ..approxbintestside = NA,
        ..varbintwos = NA,
        ..splitbin = NA,
        ..binalphaindep = NA,
        ..twosamplesbintest = NA,
        ..twosamplesbintestside = NA,
        ..varnonparamones = NA,
        ..nonparamalphaones = NA,
        ..signtest = NA,
        ..signtestvalue = NA,
        ..signtestside = NA,
        ..varnonparamtwos = NA,
        ..splitnonparam = NA,
        ..nonparamalphatwos = NA,
        ..utest = NA,
        ..utestside = NA,
        ..nominal1 = NA,
        ..nominal2 = NA,
        ..counts = NA,
        ..contabs = NA,
        ..conttest = NA,
        ..conttestalpha = NA)
)

d6testsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d6testsResults",
    inherit = jmvcore::Group,
    active = list(
        ztest = function() private$.items[["ztest"]],
        ttest = function() private$.items[["ttest"]],
        chitestknownmu = function() private$.items[["chitestknownmu"]],
        chitest = function() private$.items[["chitest"]],
        ztestpaired = function() private$.items[["ztestpaired"]],
        ttestpaired = function() private$.items[["ttestpaired"]],
        indeptestpaired = function() private$.items[["indeptestpaired"]],
        ftest = function() private$.items[["ftest"]],
        ztestindep = function() private$.items[["ztestindep"]],
        ttestindep = function() private$.items[["ttestindep"]],
        exactbintest = function() private$.items[["exactbintest"]],
        approxbintest = function() private$.items[["approxbintest"]],
        approxtwosamplebintest = function() private$.items[["approxtwosamplebintest"]],
        signtest = function() private$.items[["signtest"]],
        utest = function() private$.items[["utest"]],
        absfreqstable = function() private$.items[["absfreqstable"]],
        contindependencetest = function() private$.items[["contindependencetest"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Statistical Tests (D6)")
            self$add(jmvcore::Table$new(
                options=options,
                name="ztest",
                title="Z-Test",
                visible="(ztest && !is.null(varnormalones))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number", 
                        `visible`="(ztest)"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number", 
                        `visible`="(ztest)"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text", 
                        `visible`="(ztest)"),
                    list(
                        `name`="power", 
                        `title`="G(\u03BC)", 
                        `type`="number", 
                        `visible`="(ztestpower)"),
                    list(
                        `name`="typeI", 
                        `title`="\u03B1(\u03BC)", 
                        `type`="number", 
                        `visible`="(ztesttypeIerror)"),
                    list(
                        `name`="typeII", 
                        `title`="\u03B2(\u03BC)", 
                        `type`="number", 
                        `visible`="(ztesttypeIIerror)"),
                    list(
                        `name`="minn", 
                        `title`="n\u2265", 
                        `type`="number", 
                        `visible`="(ztestexpdesign)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ttest",
                title="t-Test",
                visible="(ttest && !is.null(varnormalones))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="chitestknownmu",
                title="\u03C7\u00B2-Test with known \u03BC",
                visible="(chitestknownmu && !is.null(varnormalones))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="d", 
                        `title`="d", 
                        `type`="number", 
                        `visible`="(chitestknownmu && chitestsideknownmu=='twochitestknownmu')"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="chitest",
                title="\u03C7\u00B2-Test with unknown \u03BC",
                visible="(chitest && !is.null(varnormalones))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="d", 
                        `title`="d", 
                        `type`="number", 
                        `visible`="(chitest && chitestside=='twochitest')"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ztestpaired",
                title="Paired samples Z-Test",
                visible="(ztestpaired && !is.null(varnormalpaired1) && !is.null(varnormalpaired2))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ttestpaired",
                title="Paired samples t-Test",
                visible="(ttestpaired && !is.null(varnormalpaired1) && !is.null(varnormalpaired2))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="indeptestpaired",
                title="Independence test for paired samples",
                visible="(indeptestpaired && !is.null(varnormalpaired1) && !is.null(varnormalpaired2))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ftest",
                title="F-Test for two variances",
                visible="(ftest && !is.null(varnormalindep))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="d", 
                        `title`="d", 
                        `type`="number", 
                        `visible`="(ftest && ftestside=='twoftest')"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ztestindep",
                title="Independent samples Z-Test",
                visible="(ztestindep && !is.null(varnormalindep))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="ttestindep",
                title="Independent samples t-Test",
                visible="(ttestindep && !is.null(varnormalindep))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="exactbintest",
                title="Exact binomial test",
                visible="(exactbintest && !is.null(varbinones))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number", 
                        `visible`="(exactbintest)"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number", 
                        `visible`="(exactbintest)"),
                    list(
                        `name`="d", 
                        `title`="d", 
                        `type`="number", 
                        `visible`="(exactbintest && exactbintestside=='twoexactbintest')"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text", 
                        `visible`="(exactbintest)"),
                    list(
                        `name`="power", 
                        `title`="G(p)", 
                        `type`="number", 
                        `visible`="(exactbintestpower)"),
                    list(
                        `name`="typeI", 
                        `title`="\u03B1(p)", 
                        `type`="number", 
                        `visible`="(exactbintesttypeIerror)"),
                    list(
                        `name`="typeII", 
                        `title`="\u03B2(p)", 
                        `type`="number", 
                        `visible`="(exactbintesttypeIIerror)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="approxbintest",
                title="Approx. binomial test",
                visible="(approxbintest && !is.null(varbinones))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="approxtwosamplebintest",
                title="Approximative two samples binomial test",
                visible="(twosamplesbintest && !is.null(varbintwos) && !is.null(splitbin))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="signtest",
                title="Sign test",
                visible="(signtest && !is.null(varnonparamones))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="d", 
                        `title`="d", 
                        `type`="number", 
                        `visible`="(signtest && signtestside=='twosigntest')"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="utest",
                title="Mann-Whitney U-Test",
                visible="(utest & !is.null(varnonparamtwos) & !is.null(splitnonparam))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="absfreqstable",
                title="Contingency table with absolute frequencies",
                visible="(contabs & !is.null(nominal1) & !is.null(nominal2))",
                columns=list()))
            self$add(jmvcore::Table$new(
                options=options,
                name="contindependencetest",
                title="\u03C7\u00B2 test for independence",
                visible="(conttest & !is.null(nominal1) & !is.null(nominal2))",
                rows=0,
                columns=list(
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))}))

d6testsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d6testsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "d6tests",
                version = c(1,0,0),
                options = options,
                results = d6testsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Statistical Tests (D6)
#'
#' 
#' @param data .
#' @param varnormalones .
#' @param normalphaones .
#' @param ztest .
#' @param ztestvalue .
#' @param ztestsigma .
#' @param ztestside .
#' @param ztestpower .
#' @param ztestpowervalue .
#' @param ztesttypeIerror .
#' @param ztesttypeIerrorvalue .
#' @param ztesttypeIIerror .
#' @param ztesttypeIIerrorvalue .
#' @param ztestexpdesign .
#' @param ztestexpdesignbeta .
#' @param ztestexpdesigndelta .
#' @param ttest .
#' @param ttestvalue .
#' @param ttestside .
#' @param chitestknownmu .
#' @param chitestvalueknownmu .
#' @param chitestmu .
#' @param chitestsideknownmu .
#' @param chitest .
#' @param chitestvalue .
#' @param chitestside .
#' @param varnormalpaired1 .
#' @param varnormalpaired2 .
#' @param normalphapaired .
#' @param ztestpaired .
#' @param ztestpairedvalue .
#' @param ztestpairedsigma1 .
#' @param ztestpairedsigma2 .
#' @param ztestpairedrho .
#' @param ztestpairedside .
#' @param ttestpaired .
#' @param ttestpairedvalue .
#' @param ttestpairedside .
#' @param indeptestpaired .
#' @param indeptestpairedside .
#' @param varnormalindep .
#' @param splitnormal .
#' @param normalphaindep .
#' @param ftest .
#' @param ftestside .
#' @param ztestindep .
#' @param ztestindepsigma .
#' @param ztestindepside .
#' @param ttestindep .
#' @param ttestindepside .
#' @param varbinones .
#' @param binalphaones .
#' @param exactbintest .
#' @param exactbintestvalue .
#' @param exactbintestside .
#' @param exactbintestpower .
#' @param exactbintestpowervalue .
#' @param exactbintesttypeIerror .
#' @param exactbintesttypeIerrorvalue .
#' @param exactbintesttypeIIerror .
#' @param exactbintesttypeIIerrorvalue .
#' @param approxbintest .
#' @param approxbintestvalue .
#' @param approxbintestside .
#' @param varbintwos .
#' @param splitbin .
#' @param binalphaindep .
#' @param twosamplesbintest .
#' @param twosamplesbintestside .
#' @param varnonparamones .
#' @param nonparamalphaones .
#' @param signtest .
#' @param signtestvalue .
#' @param signtestside .
#' @param varnonparamtwos .
#' @param splitnonparam .
#' @param nonparamalphatwos .
#' @param utest .
#' @param utestside .
#' @param nominal1 .
#' @param nominal2 .
#' @param counts .
#' @param contabs .
#' @param conttest .
#' @param conttestalpha .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$ztest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ttest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$chitestknownmu} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$chitest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ztestpaired} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ttestpaired} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$indeptestpaired} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ftest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ztestindep} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$ttestindep} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$exactbintest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$approxbintest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$approxtwosamplebintest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$signtest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$utest} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$absfreqstable} \tab \tab \tab \tab \tab a table of proportions \cr
#'   \code{results$contindependencetest} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$ztest$asDF}
#'
#' \code{as.data.frame(results$ztest)}
#'
#' @export
d6tests <- function(
    data,
    varnormalones,
    normalphaones = 0.05,
    ztest = FALSE,
    ztestvalue = 1,
    ztestsigma = 0.1,
    ztestside = "twoztest",
    ztestpower = FALSE,
    ztestpowervalue = 1,
    ztesttypeIerror = FALSE,
    ztesttypeIerrorvalue = 1,
    ztesttypeIIerror = FALSE,
    ztesttypeIIerrorvalue = 1,
    ztestexpdesign = FALSE,
    ztestexpdesignbeta = 0.5,
    ztestexpdesigndelta = 1,
    ttest = FALSE,
    ttestvalue = 1,
    ttestside = "twottest",
    chitestknownmu = FALSE,
    chitestvalueknownmu = 1,
    chitestmu = 2,
    chitestsideknownmu = "twochitestknownmu",
    chitest = FALSE,
    chitestvalue = 1,
    chitestside = "twochitest",
    varnormalpaired1,
    varnormalpaired2,
    normalphapaired = 0.05,
    ztestpaired = FALSE,
    ztestpairedvalue = 1,
    ztestpairedsigma1 = 1,
    ztestpairedsigma2 = 1,
    ztestpairedrho = 0.1,
    ztestpairedside = "twoztestpaired",
    ttestpaired = FALSE,
    ttestpairedvalue = 1,
    ttestpairedside = "twottestpaired",
    indeptestpaired = FALSE,
    indeptestpairedside = "twoindeptestpaired",
    varnormalindep,
    splitnormal,
    normalphaindep = 0.05,
    ftest = FALSE,
    ftestside = "twoftest",
    ztestindep = FALSE,
    ztestindepsigma = 0.1,
    ztestindepside = "twoztestindep",
    ttestindep = FALSE,
    ttestindepside = "twottestindep",
    varbinones,
    binalphaones = 0.05,
    exactbintest = FALSE,
    exactbintestvalue = 0.5,
    exactbintestside = "twoexactbintest",
    exactbintestpower = FALSE,
    exactbintestpowervalue = 0.5,
    exactbintesttypeIerror = FALSE,
    exactbintesttypeIerrorvalue = 0.1,
    exactbintesttypeIIerror = FALSE,
    exactbintesttypeIIerrorvalue = 0.1,
    approxbintest = FALSE,
    approxbintestvalue = 0.5,
    approxbintestside = "twoapproxbintest",
    varbintwos,
    splitbin,
    binalphaindep = 0.05,
    twosamplesbintest = FALSE,
    twosamplesbintestside = "twotwosamplesbintest",
    varnonparamones,
    nonparamalphaones = 0.05,
    signtest = FALSE,
    signtestvalue = 0,
    signtestside = "twosigntest",
    varnonparamtwos,
    splitnonparam,
    nonparamalphatwos = 0.05,
    utest = FALSE,
    utestside = "twoutest",
    nominal1,
    nominal2,
    counts,
    contabs = FALSE,
    conttest = FALSE,
    conttestalpha = 0.05) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("d6tests requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varnormalones)) varnormalones <- jmvcore::resolveQuo(jmvcore::enquo(varnormalones))
    if ( ! missing(varnormalpaired1)) varnormalpaired1 <- jmvcore::resolveQuo(jmvcore::enquo(varnormalpaired1))
    if ( ! missing(varnormalpaired2)) varnormalpaired2 <- jmvcore::resolveQuo(jmvcore::enquo(varnormalpaired2))
    if ( ! missing(varnormalindep)) varnormalindep <- jmvcore::resolveQuo(jmvcore::enquo(varnormalindep))
    if ( ! missing(splitnormal)) splitnormal <- jmvcore::resolveQuo(jmvcore::enquo(splitnormal))
    if ( ! missing(varbinones)) varbinones <- jmvcore::resolveQuo(jmvcore::enquo(varbinones))
    if ( ! missing(varbintwos)) varbintwos <- jmvcore::resolveQuo(jmvcore::enquo(varbintwos))
    if ( ! missing(splitbin)) splitbin <- jmvcore::resolveQuo(jmvcore::enquo(splitbin))
    if ( ! missing(varnonparamones)) varnonparamones <- jmvcore::resolveQuo(jmvcore::enquo(varnonparamones))
    if ( ! missing(varnonparamtwos)) varnonparamtwos <- jmvcore::resolveQuo(jmvcore::enquo(varnonparamtwos))
    if ( ! missing(splitnonparam)) splitnonparam <- jmvcore::resolveQuo(jmvcore::enquo(splitnonparam))
    if ( ! missing(nominal1)) nominal1 <- jmvcore::resolveQuo(jmvcore::enquo(nominal1))
    if ( ! missing(nominal2)) nominal2 <- jmvcore::resolveQuo(jmvcore::enquo(nominal2))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varnormalones), varnormalones, NULL),
            `if`( ! missing(varnormalpaired1), varnormalpaired1, NULL),
            `if`( ! missing(varnormalpaired2), varnormalpaired2, NULL),
            `if`( ! missing(varnormalindep), varnormalindep, NULL),
            `if`( ! missing(splitnormal), splitnormal, NULL),
            `if`( ! missing(varbinones), varbinones, NULL),
            `if`( ! missing(varbintwos), varbintwos, NULL),
            `if`( ! missing(splitbin), splitbin, NULL),
            `if`( ! missing(varnonparamones), varnonparamones, NULL),
            `if`( ! missing(varnonparamtwos), varnonparamtwos, NULL),
            `if`( ! missing(splitnonparam), splitnonparam, NULL),
            `if`( ! missing(nominal1), nominal1, NULL),
            `if`( ! missing(nominal2), nominal2, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in splitnormal) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in splitbin) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in splitnonparam) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- d6testsOptions$new(
        varnormalones = varnormalones,
        normalphaones = normalphaones,
        ztest = ztest,
        ztestvalue = ztestvalue,
        ztestsigma = ztestsigma,
        ztestside = ztestside,
        ztestpower = ztestpower,
        ztestpowervalue = ztestpowervalue,
        ztesttypeIerror = ztesttypeIerror,
        ztesttypeIerrorvalue = ztesttypeIerrorvalue,
        ztesttypeIIerror = ztesttypeIIerror,
        ztesttypeIIerrorvalue = ztesttypeIIerrorvalue,
        ztestexpdesign = ztestexpdesign,
        ztestexpdesignbeta = ztestexpdesignbeta,
        ztestexpdesigndelta = ztestexpdesigndelta,
        ttest = ttest,
        ttestvalue = ttestvalue,
        ttestside = ttestside,
        chitestknownmu = chitestknownmu,
        chitestvalueknownmu = chitestvalueknownmu,
        chitestmu = chitestmu,
        chitestsideknownmu = chitestsideknownmu,
        chitest = chitest,
        chitestvalue = chitestvalue,
        chitestside = chitestside,
        varnormalpaired1 = varnormalpaired1,
        varnormalpaired2 = varnormalpaired2,
        normalphapaired = normalphapaired,
        ztestpaired = ztestpaired,
        ztestpairedvalue = ztestpairedvalue,
        ztestpairedsigma1 = ztestpairedsigma1,
        ztestpairedsigma2 = ztestpairedsigma2,
        ztestpairedrho = ztestpairedrho,
        ztestpairedside = ztestpairedside,
        ttestpaired = ttestpaired,
        ttestpairedvalue = ttestpairedvalue,
        ttestpairedside = ttestpairedside,
        indeptestpaired = indeptestpaired,
        indeptestpairedside = indeptestpairedside,
        varnormalindep = varnormalindep,
        splitnormal = splitnormal,
        normalphaindep = normalphaindep,
        ftest = ftest,
        ftestside = ftestside,
        ztestindep = ztestindep,
        ztestindepsigma = ztestindepsigma,
        ztestindepside = ztestindepside,
        ttestindep = ttestindep,
        ttestindepside = ttestindepside,
        varbinones = varbinones,
        binalphaones = binalphaones,
        exactbintest = exactbintest,
        exactbintestvalue = exactbintestvalue,
        exactbintestside = exactbintestside,
        exactbintestpower = exactbintestpower,
        exactbintestpowervalue = exactbintestpowervalue,
        exactbintesttypeIerror = exactbintesttypeIerror,
        exactbintesttypeIerrorvalue = exactbintesttypeIerrorvalue,
        exactbintesttypeIIerror = exactbintesttypeIIerror,
        exactbintesttypeIIerrorvalue = exactbintesttypeIIerrorvalue,
        approxbintest = approxbintest,
        approxbintestvalue = approxbintestvalue,
        approxbintestside = approxbintestside,
        varbintwos = varbintwos,
        splitbin = splitbin,
        binalphaindep = binalphaindep,
        twosamplesbintest = twosamplesbintest,
        twosamplesbintestside = twosamplesbintestside,
        varnonparamones = varnonparamones,
        nonparamalphaones = nonparamalphaones,
        signtest = signtest,
        signtestvalue = signtestvalue,
        signtestside = signtestside,
        varnonparamtwos = varnonparamtwos,
        splitnonparam = splitnonparam,
        nonparamalphatwos = nonparamalphatwos,
        utest = utest,
        utestside = utestside,
        nominal1 = nominal1,
        nominal2 = nominal2,
        counts = counts,
        contabs = contabs,
        conttest = conttest,
        conttestalpha = conttestalpha)

    analysis <- d6testsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

