
# This file is automatically generated, you probably don't want to edit this

d7linearregressionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d7linearregressionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            yvariable = NULL,
            xvariable = NULL,
            linReg = FALSE,
            ser = FALSE,
            varest = FALSE,
            confia = FALSE,
            confsidea = "twoconfa",
            confiaknownsigma = FALSE,
            confiaknownsigmavalue = 1,
            confib = FALSE,
            confsideb = "twoconfb",
            confibknownsigma = FALSE,
            confibknownsigmavalue = 1,
            confisigma = FALSE,
            confsidesigma = "twoconfsigma",
            confif = FALSE,
            confifvalue = 1,
            confalpha = 0.95,
            confibandf = FALSE,
            hypalpha = 0.05,
            hyptesta = FALSE,
            testvaluea = 1,
            hyttestsidea = "twoa",
            hyptestaknownsigma = FALSE,
            hyptestaknownsigmavalue = 1,
            hyptestb = FALSE,
            testvalueb = 1,
            hyttestsideb = "twob",
            hyptestbknownsigma = FALSE,
            hyptestbknownsigmavalue = 1,
            hyptestsigma = FALSE,
            testvaluesigma = 1,
            hyttestsidesigma = "twosigma", ...) {

            super$initialize(
                package="jamoviRWTH",
                name="d7linearregression",
                requiresData=TRUE,
                ...)

            private$..yvariable <- jmvcore::OptionVariable$new(
                "yvariable",
                yvariable,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..xvariable <- jmvcore::OptionVariable$new(
                "xvariable",
                xvariable,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..linReg <- jmvcore::OptionBool$new(
                "linReg",
                linReg,
                default=FALSE)
            private$..ser <- jmvcore::OptionBool$new(
                "ser",
                ser,
                default=FALSE)
            private$..varest <- jmvcore::OptionBool$new(
                "varest",
                varest,
                default=FALSE)
            private$..confia <- jmvcore::OptionBool$new(
                "confia",
                confia,
                default=FALSE)
            private$..confsidea <- jmvcore::OptionList$new(
                "confsidea",
                confsidea,
                options=list(
                    "twoconfa",
                    "lowerconfa",
                    "upperconfa"),
                default="twoconfa")
            private$..confiaknownsigma <- jmvcore::OptionBool$new(
                "confiaknownsigma",
                confiaknownsigma,
                default=FALSE)
            private$..confiaknownsigmavalue <- jmvcore::OptionNumber$new(
                "confiaknownsigmavalue",
                confiaknownsigmavalue,
                default=1)
            private$..confib <- jmvcore::OptionBool$new(
                "confib",
                confib,
                default=FALSE)
            private$..confsideb <- jmvcore::OptionList$new(
                "confsideb",
                confsideb,
                options=list(
                    "twoconfb",
                    "lowerconfb",
                    "upperconfb"),
                default="twoconfb")
            private$..confibknownsigma <- jmvcore::OptionBool$new(
                "confibknownsigma",
                confibknownsigma,
                default=FALSE)
            private$..confibknownsigmavalue <- jmvcore::OptionNumber$new(
                "confibknownsigmavalue",
                confibknownsigmavalue,
                default=1)
            private$..confisigma <- jmvcore::OptionBool$new(
                "confisigma",
                confisigma,
                default=FALSE)
            private$..confsidesigma <- jmvcore::OptionList$new(
                "confsidesigma",
                confsidesigma,
                options=list(
                    "twoconfsigma",
                    "lowerconfsigma",
                    "upperconfsigma"),
                default="twoconfsigma")
            private$..confif <- jmvcore::OptionBool$new(
                "confif",
                confif,
                default=FALSE)
            private$..confifvalue <- jmvcore::OptionNumber$new(
                "confifvalue",
                confifvalue,
                default=1)
            private$..confalpha <- jmvcore::OptionNumber$new(
                "confalpha",
                confalpha,
                default=0.95)
            private$..confibandf <- jmvcore::OptionBool$new(
                "confibandf",
                confibandf,
                default=FALSE)
            private$..hypalpha <- jmvcore::OptionNumber$new(
                "hypalpha",
                hypalpha,
                default=0.05)
            private$..hyptesta <- jmvcore::OptionBool$new(
                "hyptesta",
                hyptesta,
                default=FALSE)
            private$..testvaluea <- jmvcore::OptionNumber$new(
                "testvaluea",
                testvaluea,
                default=1)
            private$..hyttestsidea <- jmvcore::OptionList$new(
                "hyttestsidea",
                hyttestsidea,
                options=list(
                    "twoa",
                    "lowera",
                    "uppera"),
                default="twoa")
            private$..hyptestaknownsigma <- jmvcore::OptionBool$new(
                "hyptestaknownsigma",
                hyptestaknownsigma,
                default=FALSE)
            private$..hyptestaknownsigmavalue <- jmvcore::OptionNumber$new(
                "hyptestaknownsigmavalue",
                hyptestaknownsigmavalue,
                default=1)
            private$..hyptestb <- jmvcore::OptionBool$new(
                "hyptestb",
                hyptestb,
                default=FALSE)
            private$..testvalueb <- jmvcore::OptionNumber$new(
                "testvalueb",
                testvalueb,
                default=1)
            private$..hyttestsideb <- jmvcore::OptionList$new(
                "hyttestsideb",
                hyttestsideb,
                options=list(
                    "twob",
                    "lowerb",
                    "upperb"),
                default="twob")
            private$..hyptestbknownsigma <- jmvcore::OptionBool$new(
                "hyptestbknownsigma",
                hyptestbknownsigma,
                default=FALSE)
            private$..hyptestbknownsigmavalue <- jmvcore::OptionNumber$new(
                "hyptestbknownsigmavalue",
                hyptestbknownsigmavalue,
                default=1)
            private$..hyptestsigma <- jmvcore::OptionBool$new(
                "hyptestsigma",
                hyptestsigma,
                default=FALSE)
            private$..testvaluesigma <- jmvcore::OptionNumber$new(
                "testvaluesigma",
                testvaluesigma,
                default=1)
            private$..hyttestsidesigma <- jmvcore::OptionList$new(
                "hyttestsidesigma",
                hyttestsidesigma,
                options=list(
                    "twosigma",
                    "lowersigma",
                    "uppersigma"),
                default="twosigma")

            self$.addOption(private$..yvariable)
            self$.addOption(private$..xvariable)
            self$.addOption(private$..linReg)
            self$.addOption(private$..ser)
            self$.addOption(private$..varest)
            self$.addOption(private$..confia)
            self$.addOption(private$..confsidea)
            self$.addOption(private$..confiaknownsigma)
            self$.addOption(private$..confiaknownsigmavalue)
            self$.addOption(private$..confib)
            self$.addOption(private$..confsideb)
            self$.addOption(private$..confibknownsigma)
            self$.addOption(private$..confibknownsigmavalue)
            self$.addOption(private$..confisigma)
            self$.addOption(private$..confsidesigma)
            self$.addOption(private$..confif)
            self$.addOption(private$..confifvalue)
            self$.addOption(private$..confalpha)
            self$.addOption(private$..confibandf)
            self$.addOption(private$..hypalpha)
            self$.addOption(private$..hyptesta)
            self$.addOption(private$..testvaluea)
            self$.addOption(private$..hyttestsidea)
            self$.addOption(private$..hyptestaknownsigma)
            self$.addOption(private$..hyptestaknownsigmavalue)
            self$.addOption(private$..hyptestb)
            self$.addOption(private$..testvalueb)
            self$.addOption(private$..hyttestsideb)
            self$.addOption(private$..hyptestbknownsigma)
            self$.addOption(private$..hyptestbknownsigmavalue)
            self$.addOption(private$..hyptestsigma)
            self$.addOption(private$..testvaluesigma)
            self$.addOption(private$..hyttestsidesigma)
        }),
    active = list(
        yvariable = function() private$..yvariable$value,
        xvariable = function() private$..xvariable$value,
        linReg = function() private$..linReg$value,
        ser = function() private$..ser$value,
        varest = function() private$..varest$value,
        confia = function() private$..confia$value,
        confsidea = function() private$..confsidea$value,
        confiaknownsigma = function() private$..confiaknownsigma$value,
        confiaknownsigmavalue = function() private$..confiaknownsigmavalue$value,
        confib = function() private$..confib$value,
        confsideb = function() private$..confsideb$value,
        confibknownsigma = function() private$..confibknownsigma$value,
        confibknownsigmavalue = function() private$..confibknownsigmavalue$value,
        confisigma = function() private$..confisigma$value,
        confsidesigma = function() private$..confsidesigma$value,
        confif = function() private$..confif$value,
        confifvalue = function() private$..confifvalue$value,
        confalpha = function() private$..confalpha$value,
        confibandf = function() private$..confibandf$value,
        hypalpha = function() private$..hypalpha$value,
        hyptesta = function() private$..hyptesta$value,
        testvaluea = function() private$..testvaluea$value,
        hyttestsidea = function() private$..hyttestsidea$value,
        hyptestaknownsigma = function() private$..hyptestaknownsigma$value,
        hyptestaknownsigmavalue = function() private$..hyptestaknownsigmavalue$value,
        hyptestb = function() private$..hyptestb$value,
        testvalueb = function() private$..testvalueb$value,
        hyttestsideb = function() private$..hyttestsideb$value,
        hyptestbknownsigma = function() private$..hyptestbknownsigma$value,
        hyptestbknownsigmavalue = function() private$..hyptestbknownsigmavalue$value,
        hyptestsigma = function() private$..hyptestsigma$value,
        testvaluesigma = function() private$..testvaluesigma$value,
        hyttestsidesigma = function() private$..hyttestsidesigma$value),
    private = list(
        ..yvariable = NA,
        ..xvariable = NA,
        ..linReg = NA,
        ..ser = NA,
        ..varest = NA,
        ..confia = NA,
        ..confsidea = NA,
        ..confiaknownsigma = NA,
        ..confiaknownsigmavalue = NA,
        ..confib = NA,
        ..confsideb = NA,
        ..confibknownsigma = NA,
        ..confibknownsigmavalue = NA,
        ..confisigma = NA,
        ..confsidesigma = NA,
        ..confif = NA,
        ..confifvalue = NA,
        ..confalpha = NA,
        ..confibandf = NA,
        ..hypalpha = NA,
        ..hyptesta = NA,
        ..testvaluea = NA,
        ..hyttestsidea = NA,
        ..hyptestaknownsigma = NA,
        ..hyptestaknownsigmavalue = NA,
        ..hyptestb = NA,
        ..testvalueb = NA,
        ..hyttestsideb = NA,
        ..hyptestbknownsigma = NA,
        ..hyptestbknownsigmavalue = NA,
        ..hyptestsigma = NA,
        ..testvaluesigma = NA,
        ..hyttestsidesigma = NA)
)

d7linearregressionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d7linearregressionResults",
    inherit = jmvcore::Group,
    active = list(
        linreg = function() private$.items[["linreg"]],
        confi = function() private$.items[["confi"]],
        confbandplot = function() private$.items[["confbandplot"]],
        hyptest = function() private$.items[["hyptest"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Linear Regression (D7)")
            self$add(jmvcore::Table$new(
                options=options,
                name="linreg",
                title="Point estimation for linear regression",
                visible="(linReg || ser || varest)",
                rows=0,
                columns=list(
                    list(
                        `name`="a_hat", 
                        `title`="\u00E2", 
                        `type`="number", 
                        `visible`="(linReg)"),
                    list(
                        `name`="b_hat", 
                        `title`="b\u0302", 
                        `type`="number", 
                        `visible`="(linReg)"),
                    list(
                        `name`="sigmahat", 
                        `title`="\u03C3\u0302 \u00B2", 
                        `type`="number", 
                        `visible`="(ser)"),
                    list(
                        `name`="sigmahat_a", 
                        `title`="\u03C3\u0302\u2090\u00B2", 
                        `type`="number", 
                        `visible`="(varest)"),
                    list(
                        `name`="sigmahat_b", 
                        `title`="\u03C3\u0302\u1D66\u00B2", 
                        `type`="number", 
                        `visible`="(varest)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="confi",
                title="Confidence intervals",
                visible="(confia || confib || confisigma || confif)",
                rows=0,
                columns=list(
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="conflevel", 
                        `title`="1-\u03B1", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="confbandplot",
                title="",
                visible="(confibandf)",
                renderFun=".confbandplot"))
            self$add(jmvcore::Table$new(
                options=options,
                name="hyptest",
                title="Hypothesis tests",
                visible="(hyptesta || hyptestb || hyptestsigma)",
                rows=0,
                columns=list(
                    list(
                        `name`="parameter", 
                        `title`="Parameter", 
                        `type`="text"),
                    list(
                        `name`="signlevel", 
                        `title`="\u03B1", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="c", 
                        `title`="c", 
                        `type`="number"),
                    list(
                        `name`="d", 
                        `title`="d", 
                        `type`="number", 
                        `visible`="(hyptestsigma && hyttestsidesigma=='twosigma')"),
                    list(
                        `name`="decision", 
                        `title`="Decision rule", 
                        `type`="text"))))}))

d7linearregressionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d7linearregressionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamoviRWTH",
                name = "d7linearregression",
                version = c(1,0,0),
                options = options,
                results = d7linearregressionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Linear Regression (D7)
#'
#' 
#' @param data .
#' @param yvariable the dependent variables (not necessary when using a
#'   formula, see the examples)
#' @param xvariable the grouping variable with two levels (not necessary when
#'   using a formula, see the examples)
#' @param linReg .
#' @param ser .
#' @param varest .
#' @param confia .
#' @param confsidea .
#' @param confiaknownsigma .
#' @param confiaknownsigmavalue .
#' @param confib .
#' @param confsideb .
#' @param confibknownsigma .
#' @param confibknownsigmavalue .
#' @param confisigma .
#' @param confsidesigma .
#' @param confif .
#' @param confifvalue .
#' @param confalpha .
#' @param confibandf .
#' @param hypalpha .
#' @param hyptesta .
#' @param testvaluea .
#' @param hyttestsidea .
#' @param hyptestaknownsigma .
#' @param hyptestaknownsigmavalue .
#' @param hyptestb .
#' @param testvalueb .
#' @param hyttestsideb .
#' @param hyptestbknownsigma .
#' @param hyptestbknownsigmavalue .
#' @param hyptestsigma .
#' @param testvaluesigma .
#' @param hyttestsidesigma .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$linreg} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$confi} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$confbandplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$hyptest} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$linreg$asDF}
#'
#' \code{as.data.frame(results$linreg)}
#'
#' @export
d7linearregression <- function(
    data,
    yvariable,
    xvariable,
    linReg = FALSE,
    ser = FALSE,
    varest = FALSE,
    confia = FALSE,
    confsidea = "twoconfa",
    confiaknownsigma = FALSE,
    confiaknownsigmavalue = 1,
    confib = FALSE,
    confsideb = "twoconfb",
    confibknownsigma = FALSE,
    confibknownsigmavalue = 1,
    confisigma = FALSE,
    confsidesigma = "twoconfsigma",
    confif = FALSE,
    confifvalue = 1,
    confalpha = 0.95,
    confibandf = FALSE,
    hypalpha = 0.05,
    hyptesta = FALSE,
    testvaluea = 1,
    hyttestsidea = "twoa",
    hyptestaknownsigma = FALSE,
    hyptestaknownsigmavalue = 1,
    hyptestb = FALSE,
    testvalueb = 1,
    hyttestsideb = "twob",
    hyptestbknownsigma = FALSE,
    hyptestbknownsigmavalue = 1,
    hyptestsigma = FALSE,
    testvaluesigma = 1,
    hyttestsidesigma = "twosigma") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("d7linearregression requires jmvcore to be installed (restart may be required)")

    if ( ! missing(yvariable)) yvariable <- jmvcore::resolveQuo(jmvcore::enquo(yvariable))
    if ( ! missing(xvariable)) xvariable <- jmvcore::resolveQuo(jmvcore::enquo(xvariable))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(yvariable), yvariable, NULL),
            `if`( ! missing(xvariable), xvariable, NULL))


    options <- d7linearregressionOptions$new(
        yvariable = yvariable,
        xvariable = xvariable,
        linReg = linReg,
        ser = ser,
        varest = varest,
        confia = confia,
        confsidea = confsidea,
        confiaknownsigma = confiaknownsigma,
        confiaknownsigmavalue = confiaknownsigmavalue,
        confib = confib,
        confsideb = confsideb,
        confibknownsigma = confibknownsigma,
        confibknownsigmavalue = confibknownsigmavalue,
        confisigma = confisigma,
        confsidesigma = confsidesigma,
        confif = confif,
        confifvalue = confifvalue,
        confalpha = confalpha,
        confibandf = confibandf,
        hypalpha = hypalpha,
        hyptesta = hyptesta,
        testvaluea = testvaluea,
        hyttestsidea = hyttestsidea,
        hyptestaknownsigma = hyptestaknownsigma,
        hyptestaknownsigmavalue = hyptestaknownsigmavalue,
        hyptestb = hyptestb,
        testvalueb = testvalueb,
        hyttestsideb = hyttestsideb,
        hyptestbknownsigma = hyptestbknownsigma,
        hyptestbknownsigmavalue = hyptestbknownsigmavalue,
        hyptestsigma = hyptestsigma,
        testvaluesigma = testvaluesigma,
        hyttestsidesigma = hyttestsidesigma)

    analysis <- d7linearregressionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

